<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>DotCraft.Dashboard</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DotCraft</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\DashBoard.html" />
    <EmbeddedResource Include="Resources\DashBoardLogin.html" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotCraft.Core\DotCraft.Core.csproj" />
  </ItemGroup>

</Project>
