using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DotCraft.Protocol.Generators;

/// <summary>Builds the deterministic AppServer RPC descriptor catalog.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class AppServerRpcCatalogGenerator : IIncrementalGenerator
{
    private const string RequestType = "DotCraft.Protocol.Contracts.RpcRequest<TParams, TResult>";
    private const string NotificationType = "DotCraft.Protocol.Contracts.RpcNotification<TParams>";

    private static readonly DiagnosticDescriptor DuplicateDescriptor = new(
        "DPC001",
        "Duplicate RPC descriptor",
        "RPC descriptor identity '{0}' is declared more than once",
        "DotCraft.Protocol",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, EmitCatalog);
    }

    private static void EmitCatalog(SourceProductionContext context, Compilation compilation)
    {
        var descriptorOwner = compilation.GetTypeByMetadataName("DotCraft.Protocol.Contracts.AppServer.AppServerRpc");
        if (descriptorOwner is null)
            return;

        var descriptors = new List<DescriptorInfo>();
        foreach (var field in descriptorOwner.GetMembers().OfType<IFieldSymbol>())
        {
            if (field.DeclaredAccessibility != Accessibility.Public || !field.IsStatic)
                continue;

            var typeName = field.Type.OriginalDefinition.ToDisplayString();
            if (typeName != RequestType && typeName != NotificationType)
                continue;

            var method = GetMethodName(field, compilation);
            if (method is null)
                continue;

            var direction = GetDirection(field, compilation) ?? string.Empty;
            var kind = typeName == RequestType ? "request" : "notification";
            descriptors.Add(new DescriptorInfo(method, direction, kind, field.Name, field.Locations.FirstOrDefault()));
        }

        var duplicates = descriptors
            .GroupBy(static descriptor => descriptor.Method + "\u001f" + descriptor.Direction + "\u001f" + descriptor.Kind, StringComparer.Ordinal)
            .Where(static group => group.Count() > 1);
        foreach (var duplicate in duplicates)
        {
            foreach (var descriptor in duplicate)
                context.ReportDiagnostic(Diagnostic.Create(DuplicateDescriptor, descriptor.Location, duplicate.Key.Replace("\u001f", "/")));
        }

        descriptors.Sort(static (left, right) =>
        {
            var byMethod = StringComparer.Ordinal.Compare(left.Method, right.Method);
            if (byMethod != 0)
                return byMethod;
            var byDirection = StringComparer.Ordinal.Compare(left.Direction, right.Direction);
            return byDirection != 0 ? byDirection : StringComparer.Ordinal.Compare(left.Kind, right.Kind);
        });

        var source = new StringBuilder(
            "// <auto-generated />\n" +
            "namespace DotCraft.Protocol.Contracts.AppServer;\n\n" +
            "/// <summary>Deterministic catalog of compiled AppServer RPC descriptors.</summary>\n" +
            "public static class AppServerRpcCatalog\n" +
            "{\n" +
            "    /// <summary>All registered descriptors sorted by wire identity.</summary>\n" +
            "    public static global::System.Collections.Generic.IReadOnlyList<global::DotCraft.Protocol.Contracts.IRpcMethodDescriptor> All { get; } =\n" +
            "    [\n");
        foreach (var descriptor in descriptors)
            source.Append("        global::DotCraft.Protocol.Contracts.AppServer.AppServerRpc.").Append(descriptor.FieldName).Append(",\n");
        source.Append("    ];\n}\n");

        context.AddSource("AppServerRpcCatalog.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        var names = new StringBuilder(
            "// <auto-generated />\n" +
            "namespace DotCraft.Protocol.Contracts.AppServer;\n\n" +
            "/// <summary>Canonical AppServer wire method names generated from the typed RPC catalog.</summary>\n" +
            "public static class AppServerMethodNames\n" +
            "{\n");
        foreach (var descriptor in descriptors.OrderBy(static descriptor => descriptor.FieldName, StringComparer.Ordinal))
        {
            names.Append("    public const string ")
                .Append(descriptor.FieldName)
                .Append(" = ")
                .Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(descriptor.Method, quote: true))
                .Append(";\n");
        }
        names.Append("}\n");

        context.AddSource("AppServerMethodNames.g.cs", SourceText.From(names.ToString(), Encoding.UTF8));
    }

    private static string? GetMethodName(IFieldSymbol field, Compilation compilation) =>
        GetConstructorArgument(field, compilation, 0);

    private static string? GetDirection(IFieldSymbol field, Compilation compilation) =>
        GetConstructorArgument(field, compilation, 1);

    private static string? GetConstructorArgument(IFieldSymbol field, Compilation compilation, int index)
    {
        var syntax = field.DeclaringSyntaxReferences.FirstOrDefault()?.GetSyntax() as VariableDeclaratorSyntax;
        var argument = syntax?.Initializer?.Value switch
        {
            ObjectCreationExpressionSyntax creation => creation.ArgumentList?.Arguments.ElementAtOrDefault(index),
            ImplicitObjectCreationExpressionSyntax creation => creation.ArgumentList.Arguments.ElementAtOrDefault(index),
            _ => null
        };
        if (argument is null)
            return null;

        var model = compilation.GetSemanticModel(argument.SyntaxTree);
        var constant = model.GetConstantValue(argument.Expression);
        if (constant.HasValue)
            return constant.Value?.ToString();

        return argument.Expression.ToString();
    }

    private sealed class DescriptorInfo
    {
        public DescriptorInfo(string method, string direction, string kind, string fieldName, Location? location)
        {
            Method = method;
            Direction = direction;
            Kind = kind;
            FieldName = fieldName;
            Location = location;
        }

        public string Method { get; }
        public string Direction { get; }
        public string Kind { get; }
        public string FieldName { get; }
        public Location? Location { get; }
    }
}
