using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DotCraft.Protocol.Generators;

/// <summary>Generates typed .NET SDK bindings from the checked-in AppServer manifest.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SdkRpcBindingsGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifest = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), "appserver.manifest.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString())
            .Where(static text => text is not null);

        context.RegisterSourceOutput(manifest.Combine(context.CompilationProvider), static (productionContext, input) =>
        {
            if (input.Right.GetTypeByMetadataName("DotCraft.Sdk.Wire.DotCraftWireClient") is null || input.Left is null)
                return;

            productionContext.AddSource("AppServerTypedRpcExtensions.g.cs", SourceText.From(Generate(input.Left), Encoding.UTF8));
        });
    }

    private static string Generate(string json)
    {
        using var document = JsonDocument.Parse(json);
        var methods = new List<Method>();
        foreach (var element in document.RootElement.GetProperty("methods").EnumerateArray())
        {
            methods.Add(new Method(
                element.GetProperty("name").GetString()!,
                element.TryGetProperty("descriptorMember", out var descriptorMember)
                    ? descriptorMember.GetString()!
                    : ToIdentifier(element.GetProperty("name").GetString()!),
                element.GetProperty("kind").GetString()!,
                element.GetProperty("direction").GetString()!,
                element.GetProperty("paramsType").GetString()!,
                element.GetProperty("resultType").GetString()!));
        }

        methods.Sort(static (left, right) => StringComparer.Ordinal.Compare(left.WireName, right.WireName));
        var source = new StringBuilder("""
            // <auto-generated />
            #nullable enable
            using System.Text.Json;
            using DotCraft.Sdk.AppServer;

            namespace DotCraft.Sdk.Wire;

            /// <summary>Typed low-level AppServer RPC bindings generated from the contract manifest.</summary>
            public static class AppServerTypedRpcExtensions
            {
            """);

        foreach (var method in methods)
        {
            var name = ToIdentifier(method.WireName);
            var paramsType = TypeName(method.ParamsType);
            var resultType = TypeName(method.ResultType);
            if (method.Direction == "clientToServer" && method.Kind == "request")
            {
                source.Append("\n    /// <summary>Sends the <c>").Append(method.WireName).Append("</c> request.</summary>\n")
                    .Append("    public static global::System.Threading.Tasks.Task<").Append(resultType).Append("> ").Append(name).AppendLine("Async(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        ").Append(paramsType).AppendLine(" parameters,")
                    .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default) =>")
                    .Append("        client.RequestAsync(global::DotCraft.Protocol.Contracts.AppServer.AppServerRpc.").Append(method.DescriptorMember).AppendLine(", parameters, cancellationToken);");
            }
            else if (method.Direction == "clientToServer")
            {
                source.Append("\n    /// <summary>Sends the <c>").Append(method.WireName).Append("</c> notification.</summary>\n")
                    .Append("    public static global::System.Threading.Tasks.Task ").Append(name).AppendLine("Async(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        ").Append(paramsType).AppendLine(" parameters,")
                    .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default) =>")
                    .Append("        client.NotifyAsync(global::DotCraft.Protocol.Contracts.AppServer.AppServerRpc.").Append(method.DescriptorMember).AppendLine(", parameters, cancellationToken);");
            }
            else if (method.Kind == "request")
            {
                source.Append("\n    /// <summary>Registers a typed handler for <c>").Append(method.WireName).Append("</c>.</summary>\n")
                    .Append("    public static global::System.IDisposable Register").Append(name).AppendLine("Handler(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        global::System.Func<").Append(paramsType).Append(", global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<").Append(resultType).AppendLine(">> handler) =>")
                    .Append("        client.RegisterServerRequestHandler(global::DotCraft.Protocol.Contracts.AppServer.AppServerRpc.").Append(method.DescriptorMember).AppendLine(", handler);");
            }
            else
            {
                source.Append("\n    /// <summary>Registers a typed handler for <c>").Append(method.WireName).Append("</c>.</summary>\n")
                    .Append("    public static global::System.IDisposable Register").Append(name).AppendLine("Handler(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        global::System.Action<").Append(paramsType).AppendLine("> handler) =>")
                    .Append("        client.RegisterNotificationHandler(global::DotCraft.Protocol.Contracts.AppServer.AppServerRpc.").Append(method.DescriptorMember).AppendLine(", handler);");
            }
        }

        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("/// <summary>Classifies AppServer notifications and deserializes every cataloged notification to its Contracts DTO.</summary>");
        source.AppendLine("public static class AppServerRunEventFactory");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>Creates a typed run event for known notifications and a raw fallback for unknown extensions.</summary>");
        source.AppendLine("    public static DotCraftRunEvent Parse(AppServerNotification notification)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(notification);");
        source.AppendLine("        return notification.Method switch");
        source.AppendLine("        {");
        foreach (var method in methods.Where(static method => method.Direction == "serverToClient" && method.Kind == "notification"))
        {
            source.Append("            \"").Append(Escape(method.WireName)).Append("\" => Create<")
                .Append(TypeName(method.ParamsType)).AppendLine(">(notification),");
        }
        source.AppendLine("            _ => new DotCraftRawRunEvent(ExtractThreadId(notification.Params) ?? string.Empty, ExtractTurnId(notification.Params), notification)");
        source.AppendLine("        };");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static DotCraftRunEvent Create<TParams>(AppServerNotification notification)");
        source.AppendLine("    {");
        source.AppendLine("        try");
        source.AppendLine("        {");
        source.AppendLine("            var parameters = notification.Params.Deserialize<TParams>(global::DotCraft.Protocol.Contracts.AppServerContractJson.Options)");
        source.AppendLine("                ?? throw new global::System.Text.Json.JsonException(\"The notification parameters were null.\");");
        source.AppendLine("            return new DotCraftRunEvent<TParams>(notification.Method, ExtractThreadId(notification.Params) ?? string.Empty, ExtractTurnId(notification.Params), parameters, notification);");
        source.AppendLine("        }");
        source.AppendLine("        catch (global::System.Exception exception) when (exception is global::System.Text.Json.JsonException or global::System.NotSupportedException)");
        source.AppendLine("        {");
        source.AppendLine("            throw new AppServerProtocolException($\"Notification '{notification.Method}' did not match its Contracts DTO.\", exception);");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static string? ExtractThreadId(JsonElement parameters)");
        source.AppendLine("    {");
        source.AppendLine("        if (parameters.ValueKind != JsonValueKind.Object) return null;");
        source.AppendLine("        if (ReadString(parameters, \"threadId\") is { } direct) return direct;");
        source.AppendLine("        if (parameters.TryGetProperty(\"turn\", out var turn) && ReadString(turn, \"threadId\") is { } fromTurn) return fromTurn;");
        source.AppendLine("        return parameters.TryGetProperty(\"thread\", out var thread) ? ReadString(thread, \"id\") : null;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static string? ExtractTurnId(JsonElement parameters)");
        source.AppendLine("    {");
        source.AppendLine("        if (parameters.ValueKind != JsonValueKind.Object) return null;");
        source.AppendLine("        if (ReadString(parameters, \"turnId\") is { } direct) return direct;");
        source.AppendLine("        return parameters.TryGetProperty(\"turn\", out var turn) ? ReadString(turn, \"id\") : null;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static string? ReadString(JsonElement value, string propertyName) =>");
        source.AppendLine("        value.ValueKind == JsonValueKind.Object && value.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.String");
        source.AppendLine("            ? property.GetString()");
        source.AppendLine("            : null;");
        source.AppendLine("}");
        return source.ToString();
    }

    private static string TypeName(string manifestType)
    {
        var name = manifestType.Substring(manifestType.IndexOf('.') + 1);
        return name == "RpcEmpty"
            ? "global::DotCraft.Protocol.Contracts.RpcEmpty"
            : "global::DotCraft.Protocol.Contracts.AppServer." + name;
    }

    private static string ToIdentifier(string wireName)
    {
        var result = new StringBuilder();
        var capitalize = true;
        foreach (var character in wireName)
        {
            if (!char.IsLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }

            result.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        return result.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class Method
    {
        public Method(string wireName, string descriptorMember, string kind, string direction, string paramsType, string resultType)
        {
            WireName = wireName;
            DescriptorMember = descriptorMember;
            Kind = kind;
            Direction = direction;
            ParamsType = paramsType;
            ResultType = resultType;
        }

        public string WireName { get; }
        public string DescriptorMember { get; }
        public string Kind { get; }
        public string Direction { get; }
        public string ParamsType { get; }
        public string ResultType { get; }
    }
}
