using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DotCraft.Protocol.Generators;

/// <summary>Generates typed .NET SDK bindings from the checked-in AppServer manifest.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class SdkRpcBindingsGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifest = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), "appserver.manifest.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString())
            .Where(static text => text is not null);

        context.RegisterSourceOutput(manifest.Combine(context.CompilationProvider), static (productionContext, input) =>
        {
            if (input.Right.GetTypeByMetadataName("DotCraft.Sdk.Wire.DotCraftWireClient") is null || input.Left is null)
                return;

            productionContext.AddSource("AppServerTypedRpcExtensions.g.cs", SourceText.From(Generate(input.Left), Encoding.UTF8));
        });
    }

    private static string Generate(string json)
    {
        using var document = JsonDocument.Parse(json);
        var methods = new List<Method>();
        foreach (var element in document.RootElement.GetProperty("methods").EnumerateArray())
        {
            methods.Add(new Method(
                element.GetProperty("name").GetString()!,
                element.GetProperty("kind").GetString()!,
                element.GetProperty("direction").GetString()!,
                element.GetProperty("paramsType").GetString()!,
                element.GetProperty("resultType").GetString()!));
        }

        methods.Sort(static (left, right) => StringComparer.Ordinal.Compare(left.WireName, right.WireName));
        var source = new StringBuilder("""
            // <auto-generated />
            #nullable enable
            using System.Text.Json;
            using DotCraft.Sdk.AppServer;

            namespace DotCraft.Sdk.Wire;

            /// <summary>Typed low-level AppServer RPC bindings generated from the contract manifest.</summary>
            public static class AppServerTypedRpcExtensions
            {
            """);

        foreach (var method in methods)
        {
            var name = ToIdentifier(method.WireName);
            var paramsType = TypeName(method.ParamsType);
            var resultType = TypeName(method.ResultType);
            if (method.Direction == "clientToServer" && method.Kind == "request")
            {
                source.Append("\n    /// <summary>Sends the <c>").Append(method.WireName).Append("</c> request.</summary>\n")
                    .Append("    public static async global::System.Threading.Tasks.Task<").Append(resultType).Append("> ").Append(name).AppendLine("Async(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        ").Append(paramsType).AppendLine(" parameters,")
                    .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)")
                    .AppendLine("    {")
                    .Append("        var result = await client.RequestRawAsync(\"").Append(Escape(method.WireName)).AppendLine("\", parameters, cancellationToken).ConfigureAwait(false);")
                    .Append("        return result.Deserialize<").Append(resultType).AppendLine(">(DotCraftJson.Options)")
                    .Append("            ?? throw new JsonException(\"AppServer returned null for ").Append(Escape(method.WireName)).AppendLine(".\");")
                    .AppendLine("    }");
            }
            else if (method.Direction == "clientToServer")
            {
                source.Append("\n    /// <summary>Sends the <c>").Append(method.WireName).Append("</c> notification.</summary>\n")
                    .Append("    public static global::System.Threading.Tasks.Task ").Append(name).AppendLine("Async(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        ").Append(paramsType).AppendLine(" parameters,")
                    .AppendLine("        global::System.Threading.CancellationToken cancellationToken = default) =>")
                    .Append("        client.NotifyRawAsync(\"").Append(Escape(method.WireName)).AppendLine("\", parameters, cancellationToken);");
            }
            else if (method.Kind == "request")
            {
                source.Append("\n    /// <summary>Registers a typed handler for <c>").Append(method.WireName).Append("</c>.</summary>\n")
                    .Append("    public static global::System.IDisposable Register").Append(name).AppendLine("Handler(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        global::System.Func<").Append(paramsType).Append(", global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<").Append(resultType).AppendLine(">> handler) =>")
                    .Append("        client.RegisterServerRequestHandlerRaw(\"").Append(Escape(method.WireName)).AppendLine("\", async (request, cancellationToken) =>")
                    .AppendLine("        {")
                    .Append("            var parameters = request.Params.Deserialize<").Append(paramsType).AppendLine(">(DotCraftJson.Options)")
                    .Append("                ?? throw new JsonException(\"AppServer sent null params for ").Append(Escape(method.WireName)).AppendLine(".\");")
                    .AppendLine("            return await handler(parameters, cancellationToken).ConfigureAwait(false);")
                    .AppendLine("        });");
            }
            else
            {
                source.Append("\n    /// <summary>Registers a typed handler for <c>").Append(method.WireName).Append("</c>.</summary>\n")
                    .Append("    public static global::System.IDisposable Register").Append(name).AppendLine("Handler(")
                    .AppendLine("        this DotCraftWireClient client,")
                    .Append("        global::System.Action<").Append(paramsType).AppendLine("> handler) =>")
                    .AppendLine("        client.RegisterNotificationHandlerRaw(notification =>")
                    .AppendLine("        {")
                    .Append("            if (!global::System.StringComparer.Ordinal.Equals(notification.Method, \"").Append(Escape(method.WireName)).AppendLine("\"))")
                    .AppendLine("                return;")
                    .Append("            var parameters = notification.Params.Deserialize<").Append(paramsType).AppendLine(">(DotCraftJson.Options)")
                    .Append("                ?? throw new JsonException(\"AppServer sent null params for ").Append(Escape(method.WireName)).AppendLine(".\");")
                    .AppendLine("            handler(parameters);")
                    .AppendLine("        });");
            }
        }

        return source.AppendLine("}").ToString();
    }

    private static string TypeName(string manifestType)
    {
        var name = manifestType.Substring(manifestType.IndexOf('.') + 1);
        return name == "RpcEmpty"
            ? "global::DotCraft.Protocol.Contracts.RpcEmpty"
            : "global::DotCraft.Protocol.Contracts.AppServer." + name;
    }

    private static string ToIdentifier(string wireName)
    {
        var result = new StringBuilder();
        var capitalize = true;
        foreach (var character in wireName)
        {
            if (!char.IsLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }

            result.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        return result.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed class Method
    {
        public Method(string wireName, string kind, string direction, string paramsType, string resultType)
        {
            WireName = wireName;
            Kind = kind;
            Direction = direction;
            ParamsType = paramsType;
            ResultType = resultType;
        }

        public string WireName { get; }
        public string Kind { get; }
        public string Direction { get; }
        public string ParamsType { get; }
        public string ResultType { get; }
    }
}
