import { type ConfigDescriptor, type ConfigGroupDescriptor } from "@dotcraft/channel";

export const configGroups: ConfigGroupDescriptor[] = [
  {
    id: "configuration",
    displayLabel: "Configuration",
    localizedDisplayLabel: {
      en: "Configuration", "zh-Hans": "配置", ja: "構成", ko: "구성",
      es: "Configuración", fr: "Configuration", de: "Konfiguration",
    },
  },
  {
    id: "advanced",
    displayLabel: "Advanced",
    localizedDisplayLabel: {
      en: "Advanced", "zh-Hans": "高级", ja: "詳細設定", ko: "고급",
      es: "Avanzado", fr: "Avancé", de: "Erweitert",
    },
  },
  {
    id: "debug",
    displayLabel: "Debug",
    localizedDisplayLabel: {
      en: "Debug", "zh-Hans": "调试", ja: "デバッグ", ko: "디버그",
      es: "Depuración", fr: "Débogage", de: "Debug",
    },
  },
];

export const configDescriptors: ConfigDescriptor[] = [
  {
    key: "dotcraft.wsUrl",
    displayLabel: "DotCraft WebSocket URL",
    description: "AppServer WebSocket endpoint (ws:// or wss://).",
    localizedDisplayLabel: {
      en: "DotCraft WebSocket URL",
      "zh-Hans": "DotCraft WebSocket 地址",
    },
    localizedDescription: {
      en: "AppServer WebSocket endpoint (ws:// or wss://).",
      "zh-Hans": "AppServer 的 WebSocket 端点（ws:// 或 wss://）。",
    },
    required: true,
    dataKind: "string",
    masked: false,
    interactiveSetupOnly: false,
    group: "configuration",
    defaultValue: "ws://127.0.0.1:9100/ws",
  },
  {
    key: "dotcraft.token",
    displayLabel: "DotCraft Token",
    description: "Optional bearer token for the DotCraft AppServer.",
    localizedDisplayLabel: {
      en: "DotCraft Token",
      "zh-Hans": "DotCraft 令牌",
    },
    localizedDescription: {
      en: "Optional bearer token for the DotCraft AppServer.",
      "zh-Hans": "DotCraft AppServer 的可选 Bearer 令牌。",
    },
    required: false,
    dataKind: "secret",
    masked: true,
    interactiveSetupOnly: false,
    group: "configuration",
  },
  {
    key: "feishu.appId",
    displayLabel: "Feishu App ID",
    description: "App ID for the Feishu bot.",
    localizedDisplayLabel: {
      en: "Feishu App ID",
      "zh-Hans": "飞书应用 ID",
    },
    localizedDescription: {
      en: "App ID for the Feishu bot.",
      "zh-Hans": "飞书 / Lark 机器人的应用 ID。",
    },
    required: true,
    dataKind: "string",
    masked: false,
    interactiveSetupOnly: false,
    group: "configuration",
  },
  {
    key: "feishu.appSecret",
    displayLabel: "Feishu App Secret",
    description: "App secret for the Feishu bot.",
    localizedDisplayLabel: {
      en: "Feishu App Secret",
      "zh-Hans": "飞书应用 Secret",
    },
    localizedDescription: {
      en: "App secret for the Feishu bot.",
      "zh-Hans": "飞书 / Lark 机器人的应用 Secret。",
    },
    required: true,
    dataKind: "secret",
    masked: true,
    interactiveSetupOnly: false,
    group: "configuration",
  },
  {
    key: "feishu.brand",
    displayLabel: "Platform",
    description: "Select the Feishu or Lark service environment.",
    localizedDisplayLabel: {
      en: "Platform",
      "zh-Hans": "服务平台",
    },
    localizedDescription: {
      en: "Select the Feishu or Lark service environment.",
      "zh-Hans": "选择接入的服务环境：飞书或 Lark。",
    },
    required: false,
    dataKind: "enum",
    masked: false,
    interactiveSetupOnly: false,
    group: "configuration",
    defaultValue: "feishu",
    options: [
      { value: "feishu", displayLabel: "Feishu", localizedDisplayLabel: { en: "Feishu", "zh-Hans": "飞书", ja: "Feishu", ko: "Feishu", es: "Feishu", fr: "Feishu", de: "Feishu" } },
      { value: "lark", displayLabel: "Lark", localizedDisplayLabel: { en: "Lark", "zh-Hans": "Lark", ja: "Lark", ko: "Lark", es: "Lark", fr: "Lark", de: "Lark" } },
    ],
  },
  {
    key: "feishu.cardTitle",
    displayLabel: "Reply Card Title",
    description: 'Brand text shown on card headers. Leave empty to use "DotCraft".',
    localizedDisplayLabel: {
      en: "Reply Card Title",
      "zh-Hans": "回复卡片标题",
    },
    localizedDescription: {
      en: 'Brand text shown on reply/progress/transcript card headers. Leave empty to use "DotCraft".',
      "zh-Hans": '回复、进度与流式卡片头部显示的品牌文本。留空则回退为 "DotCraft"。',
    },
    required: false,
    dataKind: "string",
    masked: false,
    interactiveSetupOnly: false,
    group: "advanced",
    defaultValue: "DotCraft",
  },
  {
    key: "feishu.streaming.enabled",
    displayLabel: "Native Streaming Cards",
    description: "Use Feishu CardKit typewriter updates and fall back to standard cards when unavailable.",
    localizedDisplayLabel: {
      en: "Native Streaming Cards",
      "zh-Hans": "原生流式卡片",
    },
    localizedDescription: {
      en: "Use Feishu CardKit typewriter updates and fall back to standard cards when unavailable.",
      "zh-Hans": "使用飞书 CardKit 打字机式更新；能力不可用时自动回退为普通卡片。",
    },
    required: false,
    dataKind: "boolean",
    masked: false,
    interactiveSetupOnly: false,
    group: "advanced",
    defaultValue: true,
  },
  {
    key: "feishu.approvalTimeoutMs",
    displayLabel: "Approval Timeout (ms)",
    description: "Timeout before approval requests auto-cancel.",
    localizedDisplayLabel: {
      en: "Approval Timeout (ms)",
      "zh-Hans": "审批超时（毫秒）",
    },
    localizedDescription: {
      en: "Timeout before approval requests auto-cancel.",
      "zh-Hans": "审批请求自动取消前的等待时长。",
    },
    required: false,
    dataKind: "number",
    masked: false,
    interactiveSetupOnly: false,
    group: "advanced",
    defaultValue: 120000,
  },
  {
    key: "feishu.groupMentionRequired",
    displayLabel: "Require @mention in Groups",
    description: "Only process group messages that mention the bot.",
    localizedDisplayLabel: {
      en: "Require @mention in Groups",
      "zh-Hans": "群聊中必须 @机器人",
    },
    localizedDescription: {
      en: "Only process group messages that mention the bot.",
      "zh-Hans": "仅处理群聊里明确 @ 机器人的消息。",
    },
    required: false,
    dataKind: "boolean",
    masked: false,
    interactiveSetupOnly: false,
    group: "configuration",
    defaultValue: true,
  },
  {
    key: "feishu.ackReactionEmoji",
    displayLabel: "Ack Reaction Emoji",
    description: "Emoji type used for inbound acknowledgement.",
    localizedDisplayLabel: {
      en: "Ack Reaction Emoji",
      "zh-Hans": "确认表情",
    },
    localizedDescription: {
      en: "Emoji type used for inbound acknowledgement.",
      "zh-Hans": "收到消息后用于确认的表情类型。",
    },
    required: false,
    dataKind: "enum",
    masked: false,
    interactiveSetupOnly: false,
    group: "advanced",
    defaultValue: "GLANCE",
    allowCustomValue: true,
    options: [
      { value: "GLANCE", displayLabel: "Glance", preview: "👀", localizedDisplayLabel: { en: "Glance", "zh-Hans": "瞥一眼", ja: "ちらり", ko: "힐끗", es: "Mirada", fr: "Coup d’œil", de: "Blick" } },
      { value: "OK", displayLabel: "OK", preview: "👌", localizedDisplayLabel: { en: "OK", "zh-Hans": "好的", ja: "OK", ko: "확인", es: "OK", fr: "OK", de: "OK" } },
      { value: "THUMBSUP", displayLabel: "Thumbs up", preview: "👍", localizedDisplayLabel: { en: "Thumbs up", "zh-Hans": "赞", ja: "いいね", ko: "좋아요", es: "Pulgar arriba", fr: "Pouce levé", de: "Daumen hoch" } },
      { value: "OnIt", displayLabel: "On it", preview: "🫡", localizedDisplayLabel: { en: "On it", "zh-Hans": "马上处理", ja: "対応中", ko: "처리 중", es: "En ello", fr: "Je m’en occupe", de: "Wird erledigt" } },
      { value: "DONE", displayLabel: "Done", preview: "✅", localizedDisplayLabel: { en: "Done", "zh-Hans": "完成", ja: "完了", ko: "완료", es: "Hecho", fr: "Terminé", de: "Erledigt" } },
      { value: "SMILE", displayLabel: "Smile", preview: "🙂", localizedDisplayLabel: { en: "Smile", "zh-Hans": "微笑", ja: "笑顔", ko: "미소", es: "Sonrisa", fr: "Sourire", de: "Lächeln" } },
    ],
  },
  {
    key: "feishu.downloadDir",
    displayLabel: "Download Directory",
    description: "Local directory for downloaded message attachments.",
    localizedDisplayLabel: {
      en: "Download Directory",
      "zh-Hans": "下载目录",
    },
    localizedDescription: {
      en: "Local directory for downloaded message attachments.",
      "zh-Hans": "下载消息附件到本地时使用的目录。",
    },
    required: false,
    dataKind: "path",
    masked: false,
    interactiveSetupOnly: false,
    group: "advanced",
  },
  {
    key: "feishu.cli.enabled",
    displayLabel: "Official Feishu CLI",
    description: "Allow this channel to use the official Feishu CLI.",
    localizedDisplayLabel: {
      en: "Official Feishu CLI", "zh-Hans": "官方飞书 CLI", ja: "公式 Feishu CLI",
      ko: "공식 Feishu CLI", es: "CLI oficial de Feishu", fr: "CLI Feishu officiel",
      de: "Offizielle Feishu-CLI",
    },
    localizedDescription: {
      en: "Allow this channel to use the official Feishu CLI.",
      "zh-Hans": "允许此渠道使用官方飞书 CLI。",
      ja: "このチャネルで公式 Feishu CLI を使用できるようにします。",
      ko: "이 채널에서 공식 Feishu CLI를 사용할 수 있도록 합니다.",
      es: "Permite que este canal use la CLI oficial de Feishu.",
      fr: "Autorise ce canal à utiliser le CLI Feishu officiel.",
      de: "Erlaubt diesem Kanal, die offizielle Feishu-CLI zu verwenden.",
    },
    required: false,
    dataKind: "boolean",
    masked: false,
    interactiveSetupOnly: false,
    group: "configuration",
    defaultValue: false,
  },
  {
    key: "feishu.debug.adapterStream",
    displayLabel: "Debug Adapter Stream",
    description: "Enable detailed adapter stream diagnostics.",
    localizedDisplayLabel: {
      en: "Debug Adapter Stream",
      "zh-Hans": "调试适配器流",
    },
    localizedDescription: {
      en: "Enable detailed adapter stream diagnostics.",
      "zh-Hans": "启用详细的适配器流诊断日志。",
    },
    required: false,
    dataKind: "boolean",
    masked: false,
    interactiveSetupOnly: false,
    group: "debug",
    defaultValue: false,
  },
  {
    key: "feishu.debug.textMerge",
    displayLabel: "Debug Text Merge",
    description: "Enable transcript merge debug logs.",
    localizedDisplayLabel: {
      en: "Debug Text Merge",
      "zh-Hans": "调试文本合并",
    },
    localizedDescription: {
      en: "Enable transcript merge debug logs.",
      "zh-Hans": "启用回复文本合并的调试日志。",
    },
    required: false,
    dataKind: "boolean",
    masked: false,
    interactiveSetupOnly: false,
    group: "debug",
    defaultValue: false,
  },
];
