using DotCraft.Configuration;

namespace DotCraft.Modules;

/// <summary>
/// Registry for managing DotCraft modules.
/// Modules are registered explicitly via <see cref="RegisterModule"/> at startup,
/// using code generated by <c>DotCraft.Generators</c>.
/// </summary>
public sealed class ModuleRegistry
{
    private readonly List<IDotCraftModule> _modules = [];

    /// <summary>
    /// Gets all registered modules.
    /// </summary>
    public IReadOnlyList<IDotCraftModule> Modules => _modules.AsReadOnly();

    /// <summary>
    /// Registers a module with its optional host factory.
    /// </summary>
    public void RegisterModule(IDotCraftModule module) => _modules.Add(module);

    /// <summary>
    /// Gets all enabled modules sorted by priority (highest first).
    /// </summary>
    public List<IDotCraftModule> GetEnabledModules(AppConfig config)
    {
        return _modules
            .Where(m => m.IsEnabled(config))
            .OrderByDescending(m => m.Priority)
            .ToList();
    }

    /// <summary>
    /// Gets enabled modules that can act as the primary host, sorted by priority (highest first).
    /// </summary>
    public List<IDotCraftModule> GetEnabledPrimaryHostModules(AppConfig config)
    {
        return GetEnabledModules(config)
            .Where(m => m.CanBePrimaryHost)
            .ToList();
    }

    /// <summary>
    /// Selects the primary module (highest priority among enabled modules).
    /// </summary>
    public IDotCraftModule? SelectPrimaryModule(AppConfig config, string? preferredModuleName = null)
    {
        var candidates = GetEnabledPrimaryHostModules(config);
        if (!string.IsNullOrWhiteSpace(preferredModuleName))
        {
            return candidates.FirstOrDefault(m =>
                string.Equals(m.Name, preferredModuleName, StringComparison.OrdinalIgnoreCase));
        }

        return candidates.FirstOrDefault();
    }

}
