export type SettingsTab =
  | 'profile'
  | 'general'
  | 'personalization'
  | 'dreams'
  | 'connection'
  | 'llmService'
  | 'browserUse'
  | 'computerControl'
  | 'usage'
  | 'archivedThreads'
  | 'mcp'
  | 'subAgents'
