// <auto-generated />
namespace DotCraft.Protocol.Contracts.AppServer;

public static partial class AppServerRpc
{    public static readonly RpcRequest<AppBindingActivateParams, AppBindingWire> AppBindingActivate = new("app/binding/activate", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppBindingRebindParams, AppBindingWire> AppBindingRebind = new("app/binding/rebind", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppBindingRequestGetParams, AppBindingRequestGetResult> AppBindingRequestGet = new("app/binding/request/get", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcNotification<AppBindingRequestedNotification> AppBindingRequested = new("app/binding/requested", RpcDirection.ServerToClient, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2");

    public static readonly RpcRequest<global::DotCraft.Protocol.Contracts.RpcEmpty, AppBindingsListResult> AppBindingsList = new("app/bindings/list", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppConnectionAuthenticateParams, AppConnectionAuthenticateResult> AppConnectionAuthenticate = new("app/connection/authenticate", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcNotification<AppConnectionChangedNotification> AppConnectionChanged = new("app/connection/changed", RpcDirection.ServerToClient, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2");

    public static readonly RpcRequest<AppConnectionConnectParams, AppConnectionConnectResult> AppConnectionConnect = new("app/connection/connect", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.Contracts.RpcEmpty, AppConnectionRefreshResult> AppConnectionRefresh = new("app/connection/refresh", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppConnectionRequestGetParams, AppConnectionRequestGetResult> AppConnectionRequestGet = new("app/connection/request/get", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppConnectionRevokeParams, AppConnectionRevokeResult> AppConnectionRevoke = new("app/connection/revoke", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppConnectionStartParams, AppConnectionStartResult> AppConnectionStart = new("app/connection/start", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppConnectionStatusParams, AppConnectionStatusResult> AppConnectionStatus = new("app/connection/status", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppListParams, AppListResult> AppList = new("app/list", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcNotification<AppListUpdatedNotification> AppListUpdated = new("app/list/updated", RpcDirection.ServerToClient, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2");

    public static readonly RpcRequest<SocialBindingAcceptParams, AppBindingWire> SocialBindingAccept = new("app/socialBinding/accept", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<SocialBindingRebindParams, AppBindingWire> SocialBindingRebind = new("app/socialBinding/rebind", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<SocialBindingRequestGetParams, AppBindingRequestWire> SocialBindingRequestGet = new("app/socialBinding/request/get", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppSocialBindingResolveParams, AppSocialBindingResolveResult> AppSocialBindingResolve = new("app/socialBinding/resolve", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppSurfacePublishParams, AppSurfaceWire> AppSurfacePublish = new("app/surface/publish", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppSurfaceResolveParams, AppSurfaceWire> AppSurfaceResolve = new("app/surface/resolve", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppThreadInputEnqueueParams, AppThreadInputEnqueueResult> AppThreadInputEnqueue = new("app/threadInput/enqueue", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AppViewParams, AppViewResult> AppView = new("app/view", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "connection", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskCreateParams, AutomationTaskCreateResult> AutomationTaskCreate = new("automation/task/create", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskDeleteParams, AutomationTaskDeleteResult> AutomationTaskDelete = new("automation/task/delete", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskDiscardWorktreeParams, AutomationTaskDiscardWorktreeResult> AutomationTaskDiscardWorktree = new("automation/task/discardWorktree", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskListParams, AutomationTaskListResult> AutomationTaskList = new("automation/task/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskReadParams, AutomationTaskWire> AutomationTaskRead = new("automation/task/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskRunParams, AutomationTaskRunResult> AutomationTaskRun = new("automation/task/run", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTaskUpdateBindingParams, AutomationTaskUpdateBindingResult> AutomationTaskUpdateBinding = new("automation/task/updateBinding", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcNotification<AutomationTaskUpdatedNotification> AutomationTaskUpdated = new("automation/task/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", notificationOptOut: true);

    public static readonly RpcRequest<AutomationTemplateDeleteParams, AutomationTemplateDeleteResult> AutomationTemplateDelete = new("automation/template/delete", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTemplateListParams, AutomationTemplateListResult> AutomationTemplateList = new("automation/template/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AutomationTemplateSaveParams, AutomationTemplateSaveResult> AutomationTemplateSave = new("automation/template/save", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);

    public static readonly RpcRequest<AcpFsReadTextFileParams, AcpFsReadTextFileResult> ExtAcpFsReadTextFile = new("ext/acp/fs/readTextFile", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<AcpFsWriteTextFileParams, AcpFsWriteTextFileResult> ExtAcpFsWriteTextFile = new("ext/acp/fs/writeTextFile", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<AcpTerminalCreateParams, AcpTerminalCreateResult> ExtAcpTerminalCreate = new("ext/acp/terminal/create", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<AcpTerminalGetOutputParams, AcpTerminalOutputResult> ExtAcpTerminalGetOutput = new("ext/acp/terminal/getOutput", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<AcpTerminalKillParams, global::DotCraft.Protocol.Contracts.RpcEmpty> ExtAcpTerminalKill = new("ext/acp/terminal/kill", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<AcpTerminalReleaseParams, global::DotCraft.Protocol.Contracts.RpcEmpty> ExtAcpTerminalRelease = new("ext/acp/terminal/release", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<AcpTerminalWaitForExitParams, AcpTerminalOutputResult> ExtAcpTerminalWaitForExit = new("ext/acp/terminal/waitForExit", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "acp", scope: "connection", capability: "acpExtensions", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.Contracts.RpcEmpty, global::DotCraft.Protocol.Contracts.RpcEmpty> ExtChannelHeartbeat = new("ext/channel/heartbeat", RpcDirection.ServerToClient, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "channelAdapter", errors: CommonErrors);

    public static readonly RpcRequest<ExtChannelSendParams, ExtChannelSendResult> ExtChannelSend = new("ext/channel/send", RpcDirection.ServerToClient, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "channelAdapter", errors: CommonErrors);

    public static readonly RpcRequest<ExtChannelToolCallParams, ExtChannelToolCallResult> ExtChannelToolCall = new("ext/channel/toolCall", RpcDirection.ServerToClient, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "channelAdapter", errors: CommonErrors);

    public static readonly RpcRequest<NodeReplCancelParams, global::DotCraft.Protocol.Contracts.RpcEmpty> ExtNodeReplCancel = new("ext/nodeRepl/cancel", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "node-repl", scope: "connection", capability: "nodeRepl", errors: CommonErrors);

    public static readonly RpcRequest<NodeReplEvaluateParams, NodeReplEvaluateResult> ExtNodeReplEvaluate = new("ext/nodeRepl/evaluate", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "node-repl", scope: "connection", capability: "nodeRepl", errors: CommonErrors);

    public static readonly RpcRequest<ExternalChannelGetParams, ExternalChannelGetResult> ExternalChannelGet = new("externalChannel/get", RpcDirection.ClientToServer, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "externalChannelManagement", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.Contracts.RpcEmpty, ExternalChannelListResult> ExternalChannelList = new("externalChannel/list", RpcDirection.ClientToServer, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "externalChannelManagement", errors: CommonErrors);

    public static readonly RpcRequest<ExternalChannelLogsParams, ExternalChannelLogsResult> ExternalChannelLogs = new("externalChannel/logs", RpcDirection.ClientToServer, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "externalChannelManagement", errors: CommonErrors);

    public static readonly RpcRequest<ExternalChannelRemoveParams, ExternalChannelRemoveResult> ExternalChannelRemove = new("externalChannel/remove", RpcDirection.ClientToServer, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "externalChannelManagement", errors: CommonErrors);

    public static readonly RpcRequest<ExternalChannelUpsertParams, ExternalChannelUpsertResult> ExternalChannelUpsert = new("externalChannel/upsert", RpcDirection.ClientToServer, "1", "specs/protocols/external-channel-adapter.md", module: "external-channel", scope: "connection", capability: "externalChannelManagement", errors: CommonErrors);

    public static readonly RpcRequest<TeamsMemberOpenThreadParams, TeamsMemberOpenThreadResult> TeamsMemberOpenThread = new("teams/member/openThread", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "teams", scope: "workspace", capability: "extensions.teams", errors: CommonErrors);

    public static readonly RpcRequest<TeamsMissionArchiveParams, TeamsTeamViewResult> TeamsMissionArchive = new("teams/mission/archive", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "teams", scope: "workspace", capability: "extensions.teams", errors: CommonErrors);

    public static readonly RpcRequest<TeamsMissionCancelParams, TeamsTeamViewResult> TeamsMissionCancel = new("teams/mission/cancel", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "teams", scope: "workspace", capability: "extensions.teams", errors: CommonErrors);

    public static readonly RpcRequest<TeamsMissionCreateParams, TeamsMissionCreateResult> TeamsMissionCreate = new("teams/mission/create", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "teams", scope: "workspace", capability: "extensions.teams", errors: CommonErrors);

    public static readonly RpcNotification<TeamsTeamChangedNotification> TeamsTeamChanged = new("teams/team/changed", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", module: "teams", scope: "workspace", capability: "extensions.teams");

    public static readonly RpcRequest<global::DotCraft.Protocol.Contracts.RpcEmpty, TeamsTeamViewResult> TeamsTeamView = new("teams/team/view", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", module: "teams", scope: "workspace", capability: "extensions.teams", errors: CommonErrors);

    public static readonly RpcNotification<ThreadAppBindingsChangedNotification> ThreadAppBindingsChanged = new("thread/appBindings/changed", RpcDirection.ServerToClient, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "thread", capability: "appBindingVersion:2");

    public static readonly RpcRequest<ThreadAppBindingConfirmCapabilitiesParams, AppBindingWire> ThreadAppBindingConfirmCapabilities = new("thread/appBindings/confirmCapabilities", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "thread", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<ThreadAppBindingEnableParams, ThreadAppBindingEnableResult> ThreadAppBindingEnable = new("thread/appBindings/enable", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "thread", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<ThreadAppBindingsListParams, ThreadAppBindingsListResult> ThreadAppBindingsList = new("thread/appBindings/list", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "thread", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<ThreadAppBindingRevokeParams, AppBindingWire> ThreadAppBindingRevoke = new("thread/appBindings/revoke", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "thread", capability: "appBindingVersion:2", errors: CommonErrors);

    public static readonly RpcRequest<ThreadSocialBindingRequestCreateParams, ThreadSocialBindingRequestCreateResult> ThreadSocialBindingRequestCreate = new("thread/socialBindings/request/create", RpcDirection.ClientToServer, "1", "specs/protocols/app-binding.md", module: "app-binding", scope: "thread", capability: "appBindingVersion:2", errors: CommonErrors);

}
