namespace DotCraft.Protocol.AppServer;

public static partial class AppServerRpc
{
    public static readonly RpcRequest<AutomationRunReadParams, AutomationRunsResult> AutomationRunsRead = new("automation/runs/read", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, AutomationListResult> AutomationList = new("automation/list", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationIdParams, AutomationReadResult> AutomationRead = new("automation/read", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationCreateParams, AutomationReadResult> AutomationCreate = new("automation/create", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationUpdateParams, AutomationReadResult> AutomationUpdate = new("automation/update", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationIdParams, AutomationDeleteResult> AutomationDelete = new("automation/delete", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationIdParams, AutomationRunResult> AutomationRun = new("automation/run", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationIdParams, AutomationRunsResult> AutomationRunsList = new("automation/runs/list", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcRequest<AutomationPresetsParams, AutomationPresetsResult> AutomationPresetsList = new("automation/presets/list", RpcDirection.ClientToServer, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", errors: CommonErrors);
    public static readonly RpcNotification<AutomationUpdatedNotification> AutomationUpdated = new("automation/updated", RpcDirection.ServerToClient, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", notificationOptOut: true);
    public static readonly RpcNotification<AutomationRunUpdatedNotification> AutomationRunUpdated = new("automation/run/updated", RpcDirection.ServerToClient, "1", "specs/features/automations-lifecycle.md", module: "automations", scope: "workspace", capability: "automations", notificationOptOut: true);
}
