// <auto-generated />
namespace DotCraft.Protocol.AppServer;

public static partial class AppServerRpc
{    public static readonly RpcRequest<AgentProfileBuilderDraftReadParams, AgentProfileBuilderDraftResult> AgentProfileBuilderDraftRead = new("agent/profiles/builderDraft/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileBuilderDraftUpdateParams, AgentProfileBuilderDraftResult> AgentProfileBuilderDraftUpdate = new("agent/profiles/builderDraft/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileListParams, AgentProfileListResult> AgentProfileList = new("agent/profiles/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileReadParams, AgentProfileReadResult> AgentProfileRead = new("agent/profiles/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileRefreshThreadParams, AgentProfileRefreshThreadResult> AgentProfileRefreshThread = new("agent/profiles/refreshThread", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileRemoveParams, AgentProfileRemoveResult> AgentProfileRemove = new("agent/profiles/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileUpsertParams, AgentProfileUpsertResult> AgentProfileUpsert = new("agent/profiles/upsert", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AgentProfileValidateParams, AgentProfileValidateResult> AgentProfileValidate = new("agent/profiles/validate", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcNotification<AuthOpenAiAuthorizeUrlNotification> AuthOpenAiAuthorizeUrl = new("auth/openai/authorizeUrl", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcRequest<AuthOpenAiLoginParams, AuthOpenAiStatusResult> AuthOpenAiLogin = new("auth/openai/login", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<AuthOpenAiLogoutParams, AuthOpenAiStatusResult> AuthOpenAiLogout = new("auth/openai/logout", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, AuthOpenAiStatusResult> AuthOpenAiStatus = new("auth/openai/status", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, AuthOpenAiUsageResult> AuthOpenAiUsage = new("auth/openai/usage", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcNotification<AuthOpenAiUsageResult> AuthOpenAiUsageChanged = new("auth/openai/usageChanged", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, ChannelListResult> ChannelList = new("channel/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, ChannelStatusResult> ChannelStatus = new("channel/status", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<CommandExecuteParams, CommandExecuteResult> CommandExecute = new("command/execute", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "commandManagement", errors: CommonErrors);

    public static readonly RpcRequest<CommandListParams, CommandListResult> CommandList = new("command/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "commandManagement", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, McpServerReloadResult> ConfigMcpServerReload = new("config/mcpServer/reload", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<CronEnableParams, CronEnableResult> CronEnable = new("cron/enable", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "cronManagement", errors: CommonErrors);

    public static readonly RpcRequest<CronListParams, CronListResult> CronList = new("cron/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "cronManagement", errors: CommonErrors);

    public static readonly RpcRequest<CronRemoveParams, CronRemoveResult> CronRemove = new("cron/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "cronManagement", errors: CommonErrors);

    public static readonly RpcRequest<CronRunParams, CronRunResult> CronRun = new("cron/run", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "cronManagement", errors: CommonErrors);

    public static readonly RpcNotification<CronStateChangedNotification> CronStateChanged = new("cron/stateChanged", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "cronManagement", notificationOptOut: true);

    public static readonly RpcRequest<DreamsRunIdParams, DreamsRunResult> DreamsApply = new("dreams/apply", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsRunIdParams, DreamsRunResult> DreamsArchive = new("dreams/archive", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsRunIdParams, DreamsRunResult> DreamsCancel = new("dreams/cancel", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsCreateParams, DreamsRunResult> DreamsCreate = new("dreams/create", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsRunIdParams, DreamsRunResult> DreamsDiscard = new("dreams/discard", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsRunIdParams, DreamsRunResult> DreamsGet = new("dreams/get", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsListParams, DreamsListResult> DreamsList = new("dreams/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsRunParams, DreamsStatusResult> DreamsRun = new("dreams/run", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<DreamsStatusParams, DreamsStatusResult> DreamsStatus = new("dreams/status", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "dreams", errors: CommonErrors);

    public static readonly RpcRequest<HooksListParams, HooksListResult> HooksList = new("hooks/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<HooksSetStateParams, HooksSetStateResult> HooksSetState = new("hooks/setState", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<HooksTrustPluginParams, HooksTrustPluginResult> HooksTrustPlugin = new("hooks/trustPlugin", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<UiResourceReadParams, UiResourceReadResult> ItemResourceRead = new("item/resource/read", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", errors: CommonErrors);

    public static readonly RpcNotification<UsageDeltaNotification> ItemUsageDelta = new("item/usage/delta", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", notificationOptOut: true);

    public static readonly RpcRequest<ItemWidgetStateSetParams, ItemWidgetStateSetResult> ItemWidgetStateSet = new("item/widget-state/set", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", errors: CommonErrors);

    public static readonly RpcRequest<MarketplaceAddParams, MarketplaceAddResult> MarketplaceAdd = new("marketplace/add", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginMarketplaces", errors: CommonErrors);

    public static readonly RpcRequest<MarketplaceRefreshParams, MarketplaceRefreshResult> MarketplaceRefresh = new("marketplace/refresh", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginMarketplaces", errors: CommonErrors);

    public static readonly RpcRequest<MarketplaceRemoveParams, MarketplaceRemoveResult> MarketplaceRemove = new("marketplace/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginMarketplaces", errors: CommonErrors);

    public static readonly RpcRequest<McpGetParams, McpGetResult> McpGet = new("mcp/get", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpManagement", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, McpListResult> McpList = new("mcp/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpManagement", errors: CommonErrors);

    public static readonly RpcRequest<McpRemoveParams, McpRemoveResult> McpRemove = new("mcp/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpManagement", errors: CommonErrors);

    public static readonly RpcRequest<McpTestParams, McpTestResult> McpTest = new("mcp/test", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpManagement", errors: CommonErrors);

    public static readonly RpcRequest<McpUpsertParams, McpUpsertResult> McpUpsert = new("mcp/upsert", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpManagement", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewCloseParams, McpAppViewCloseResult> McpAppViewClose = new("mcpApp/view/close", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewMessageParams, McpAppViewMessageResult> McpAppViewMessage = new("mcpApp/view/message", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewModelContextUpdateParams, McpAppViewModelContextUpdateResult> McpAppViewModelContextUpdate = new("mcpApp/view/modelContext/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewOpenParams, McpAppViewOpenResult> McpAppViewOpen = new("mcpApp/view/open", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewOpenLinkParams, McpAppViewOpenLinkResult> McpAppViewOpenLink = new("mcpApp/view/openLink", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewResourceReadParams, McpAppViewResourceReadResult> McpAppViewResourceRead = new("mcpApp/view/resource/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcNotification<McpAppViewStatusUpdatedParams> McpAppViewStatusUpdated = new("mcpApp/view/status/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", notificationOptOut: true);

    public static readonly RpcRequest<McpAppViewToolCallParams, McpAppToolResult> McpAppViewToolCall = new("mcpApp/view/tool/call", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpAppViewToolsListParams, McpAppViewToolsListResult> McpAppViewToolsList = new("mcpApp/view/tools/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpApps", errors: CommonErrors);

    public static readonly RpcRequest<McpServerElicitationRequestParams, McpServerElicitationResponse> McpServerElicitationRequest = new("mcpServer/elicitation/request", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpElicitation", errors: CommonErrors);

    public static readonly RpcRequest<McpServerOAuthLoginParams, McpServerOAuthLoginResult> McpServerOAuthLogin = new("mcpServer/oauth/login", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpRuntime", errors: CommonErrors);

    public static readonly RpcNotification<McpServerOAuthLoginCompletedNotification> McpServerOAuthLoginCompleted = new("mcpServer/oauthLogin/completed", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpRuntime", notificationOptOut: true);

    public static readonly RpcRequest<McpServerResourceReadParams, McpServerResourceReadResult> McpServerResourceRead = new("mcpServer/resource/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpRuntime", errors: CommonErrors);

    public static readonly RpcNotification<McpServerStartupStatusUpdatedNotification> McpServerStartupStatusUpdated = new("mcpServer/startupStatus/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpRuntime", notificationOptOut: true);

    public static readonly RpcRequest<McpServerToolCallParams, McpServerToolCallResult> McpServerToolCall = new("mcpServer/tool/call", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "mcpRuntime", errors: CommonErrors);

    public static readonly RpcRequest<McpServerStatusListParams, McpServerStatusListResult> McpServerStatusList = new("mcpServerStatus/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, MemoryResetResult> MemoryReset = new("memory/reset", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<ModelListParams, ModelListResult> ModelList = new("model/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "modelCatalogManagement", errors: CommonErrors);

    public static readonly RpcNotification<PlanUpdatedNotification> PlanUpdated = new("plan/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcRequest<PluginInstallParams, PluginOperationResult> PluginInstall = new("plugin/install", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcRequest<PluginInstallLocalParams, PluginOperationResult> PluginInstallLocal = new("plugin/installLocal", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcRequest<PluginConfigGetParams, PluginConfigSnapshot> PluginConfigGet = new("plugin/config/get", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginConfiguration", errors: PluginConfigErrors);

    public static readonly RpcRequest<PluginConfigMutateParams, PluginConfigSnapshot> PluginConfigMutate = new("plugin/config/mutate", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginConfiguration", errors: PluginConfigErrors);

    public static readonly RpcRequest<PluginListParams, PluginListResult> PluginList = new("plugin/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcRequest<PluginRemoveParams, PluginOperationResult> PluginRemove = new("plugin/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcRequest<PluginSetEnabledParams, PluginOperationResult> PluginSetEnabled = new("plugin/setEnabled", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcRequest<PluginSetTrustedParams, PluginOperationResult> PluginSetTrusted = new("plugin/setTrusted", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcNotification<PluginSnapshotUpdatedNotification> PluginSnapshotUpdated = new("plugin/snapshot/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", notificationOptOut: true);

    public static readonly RpcRequest<PluginViewParams, PluginViewResult> PluginView = new("plugin/view", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "pluginManagement", errors: CommonErrors);

    public static readonly RpcRequest<ProfileInsightsParams, ProfileInsightsResult> ProfileInsights = new("profile/insights", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<ProviderCreateParams, ProviderMutationResult> ProviderCreate = new("provider/create", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "providerManagement", errors: CommonErrors);

    public static readonly RpcRequest<ProviderDeleteParams, ProviderDeleteResult> ProviderDelete = new("provider/delete", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "providerManagement", errors: CommonErrors);

    public static readonly RpcRequest<ProviderListParams, ProviderListResult> ProviderList = new("provider/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "providerManagement", errors: CommonErrors);

    public static readonly RpcRequest<ProviderTestParams, ProviderTestResult> ProviderTest = new("provider/test", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "providerManagement", errors: CommonErrors);

    public static readonly RpcRequest<ProviderUpdateParams, ProviderMutationResult> ProviderUpdate = new("provider/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "providerManagement", errors: CommonErrors);

    public static readonly RpcRequest<SkillsListParams, SkillsListResult> SkillsList = new("skills/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "skillsManagement", errors: CommonErrors);

    public static readonly RpcRequest<SkillsReadParams, SkillsReadResult> SkillsRead = new("skills/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "skillsManagement", errors: CommonErrors);

    public static readonly RpcRequest<SkillsRestoreOriginalParams, SkillsRestoreOriginalResult> SkillsRestoreOriginal = new("skills/restoreOriginal", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "skillsManagement", errors: CommonErrors);

    public static readonly RpcRequest<SkillsSetEnabledParams, SkillsSetEnabledResult> SkillsSetEnabled = new("skills/setEnabled", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "skillsManagement", errors: CommonErrors);

    public static readonly RpcRequest<SkillsUninstallParams, SkillsUninstallResult> SkillsUninstall = new("skills/uninstall", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "skillsManagement", errors: CommonErrors);

    public static readonly RpcRequest<SkillsViewParams, SkillsViewResult> SkillsView = new("skills/view", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "skillsManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlChangelistCreateParams, SourceControlChangelistCreateResult> SourceControlChangelistCreate = new("sourceControl/changelist/create", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlChangelistListParams, SourceControlChangelistListResult> SourceControlChangelistList = new("sourceControl/changelist/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlChangelistPrepareParams, SourceControlChangelistPrepareResult> SourceControlChangelistPrepare = new("sourceControl/changelist/prepare", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlGetParams, SourceControlSnapshot> SourceControlGet = new("sourceControl/get", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlTestParams, SourceControlTestResult> SourceControlTest = new("sourceControl/test", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlThreadTargetParams, SourceControlThreadTargetResult> SourceControlThreadTargetGet = new("sourceControl/threadTarget/get", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlThreadTargetUpdateParams, SourceControlThreadTargetResult> SourceControlThreadTargetUpdate = new("sourceControl/threadTarget/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SourceControlUpdateParams, SourceControlSnapshot> SourceControlUpdate = new("sourceControl/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "sourceControlManagement", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentChildrenListParams, SubAgentChildrenListResult> SubAgentChildrenList = new("subagent/children/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentTargetParams, SubAgentControlResult> SubAgentClose = new("subagent/close", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentTargetMessageParams, SubAgentControlResult> SubAgentFollowupTask = new("subagent/followupTask", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcNotification<SubAgentGraphChangedNotification> SubAgentGraphChanged = new("subagent/graphChanged", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, SubAgentProfileListResult> SubAgentProfileList = new("subagent/profiles/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentProfileRemoveParams, SubAgentProfileRemoveResult> SubAgentProfileRemove = new("subagent/profiles/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentProfileSetEnabledParams, SubAgentProfileSetEnabledResult> SubAgentProfileSetEnabled = new("subagent/profiles/setEnabled", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentProfileUpsertParams, SubAgentProfileUpsertResult> SubAgentProfileUpsert = new("subagent/profiles/upsert", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcNotification<SubAgentProgressNotification> SubAgentProgress = new("subagent/progress", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcRequest<SubAgentTargetMessageParams, SubAgentControlResult> SubAgentSendMessage = new("subagent/sendMessage", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<SubAgentSettingsUpdateParams, SubAgentSettingsUpdateResult> SubAgentSettingsUpdate = new("subagent/settings/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcNotification<SystemEventNotification> SystemEvent = new("system/event", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcNotification<SystemJobResultNotification> SystemJobResult = new("system/jobResult", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "connection", notificationOptOut: true);

    public static readonly RpcRequest<TerminalCleanParams, TerminalCleanResult> TerminalClean = new("terminal/clean", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", errors: CommonErrors);

    public static readonly RpcNotification<TerminalLifecycleNotification> TerminalCleaned = new("terminal/cleaned", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", notificationOptOut: true);

    public static readonly RpcNotification<TerminalLifecycleNotification> TerminalCompleted = new("terminal/completed", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", notificationOptOut: true);

    public static readonly RpcRequest<TerminalListParams, TerminalListResult> TerminalList = new("terminal/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", errors: CommonErrors);

    public static readonly RpcNotification<TerminalLifecycleNotification> TerminalOutputDelta = new("terminal/outputDelta", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", notificationOptOut: true);

    public static readonly RpcRequest<TerminalReadParams, TerminalReadResult> TerminalRead = new("terminal/read", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", errors: CommonErrors);

    public static readonly RpcNotification<TerminalLifecycleNotification> TerminalStalled = new("terminal/stalled", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", notificationOptOut: true);

    public static readonly RpcNotification<TerminalLifecycleNotification> TerminalStarted = new("terminal/started", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", notificationOptOut: true);

    public static readonly RpcRequest<TerminalStopParams, TerminalStopResult> TerminalStop = new("terminal/stop", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", errors: CommonErrors);

    public static readonly RpcRequest<TerminalWriteParams, TerminalWriteResult> TerminalWrite = new("terminal/write", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "backgroundTerminals", errors: CommonErrors);

    public static readonly RpcRequest<ThreadArchiveParams, global::DotCraft.Protocol.RpcEmpty> ThreadArchive = new("thread/archive", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadCompactStartParams, ThreadCompactStartResponse> ThreadCompactStart = new("thread/compact/start", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadConfigUpdateParams, global::DotCraft.Protocol.RpcEmpty> ThreadConfigUpdate = new("thread/config/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadDeleteParams, global::DotCraft.Protocol.RpcEmpty> ThreadDelete = new("thread/delete", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadForkParams, ThreadForkResult> ThreadFork = new("thread/fork", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadGoalClearParams, ThreadGoalClearResult> ThreadGoalClear = new("thread/goal/clear", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcNotification<ThreadGoalClearedNotification> ThreadGoalCleared = new("thread/goal/cleared", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", notificationOptOut: true);

    public static readonly RpcRequest<ThreadGoalGetParams, ThreadGoalGetResult> ThreadGoalGet = new("thread/goal/get", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadGoalSetParams, ThreadGoalSetResult> ThreadGoalSet = new("thread/goal/set", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcNotification<ThreadGoalUpdatedNotification> ThreadGoalUpdated = new("thread/goal/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", notificationOptOut: true);

    public static readonly RpcRequest<ThreadMaintenanceInterruptParams, global::DotCraft.Protocol.RpcEmpty> ThreadMaintenanceInterrupt = new("thread/maintenance/interrupt", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadMemoryConsolidateStartParams, ThreadMemoryConsolidateStartResponse> ThreadMemoryConsolidateStart = new("thread/memory/consolidate/start", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadModeSetParams, global::DotCraft.Protocol.RpcEmpty> ThreadModeSet = new("thread/mode/set", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadPauseParams, global::DotCraft.Protocol.RpcEmpty> ThreadPause = new("thread/pause", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcNotification<ThreadQueueUpdatedNotification> ThreadQueueUpdated = new("thread/queue/updated", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", notificationOptOut: true);

    public static readonly RpcRequest<ThreadRenameParams, global::DotCraft.Protocol.RpcEmpty> ThreadRename = new("thread/rename", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcNotification<ThreadRenamedNotification> ThreadRenamed = new("thread/renamed", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", notificationOptOut: true);

    public static readonly RpcRequest<ThreadRollbackParams, ThreadRollbackResponse> ThreadRollback = new("thread/rollback", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcNotification<ThreadRuntimeChangedParams> ThreadRuntimeChanged = new("thread/runtimeChanged", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", notificationOptOut: true);

    public static readonly RpcNotification<ThreadStatusChangedNotification> ThreadStatusChanged = new("thread/statusChanged", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", notificationOptOut: true);

    public static readonly RpcRequest<ThreadSubscribeParams, global::DotCraft.Protocol.RpcEmpty> ThreadSubscribe = new("thread/subscribe", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadUnarchiveParams, global::DotCraft.Protocol.RpcEmpty> ThreadUnarchive = new("thread/unarchive", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadUnsubscribeParams, global::DotCraft.Protocol.RpcEmpty> ThreadUnsubscribe = new("thread/unsubscribe", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ThreadWorktreeHandoffParams, ThreadWorktreeHandoffResponse> ThreadWorktreeHandoff = new("thread/worktree/handoff", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", capability: "threadManagement", errors: CommonErrors);

    public static readonly RpcRequest<ToolListParams, ToolListResult> ToolList = new("tool/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<TurnQueueRemoveParams, TurnQueueRemoveResponse> TurnQueueRemove = new("turn/queue/remove", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", errors: CommonErrors);

    public static readonly RpcRequest<TurnQueueReorderParams, TurnQueueReorderResponse> TurnQueueReorder = new("turn/queue/reorder", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", errors: CommonErrors);

    public static readonly RpcRequest<TurnQueueUpdateParams, TurnQueueUpdateResult> TurnQueueUpdate = new("turn/queue/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "thread", errors: CommonErrors);

    public static readonly RpcRequest<global::DotCraft.Protocol.RpcEmpty, UsageSummaryResult> UsageSummary = new("usage/summary", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<UsageTimeseriesParams, UsageTimeseriesResult> UsageTimeseries = new("usage/timeseries", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<InlineVisualizationViewCloseParams, InlineVisualizationViewCloseResult> InlineVisualizationViewClose = new("visualization/view/close", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "inlineVisualizations", errors: CommonErrors);

    public static readonly RpcRequest<InlineVisualizationViewMessageParams, InlineVisualizationViewMessageResult> InlineVisualizationViewMessage = new("visualization/view/message", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "inlineVisualizations", errors: CommonErrors);

    public static readonly RpcRequest<InlineVisualizationViewOpenParams, InlineVisualizationViewOpenResult> InlineVisualizationViewOpen = new("visualization/view/open", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", capability: "inlineVisualizations", errors: CommonErrors);

    public static readonly RpcRequest<WelcomeSuggestionsParams, WelcomeSuggestionsResult> WelcomeSuggestions = new("welcome/suggestions", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "connection", errors: CommonErrors);

    public static readonly RpcRequest<WorkspaceCommitMessageSuggestParams, WorkspaceCommitMessageSuggestResult> WorkspaceCommitMessageSuggest = new("workspace/commitMessage/suggest", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

    public static readonly RpcRequest<WorkspaceConfigSchemaParams, WorkspaceConfigSchemaResult> WorkspaceConfigSchema = new("workspace/config/schema", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

    public static readonly RpcRequest<WorkspaceConfigUpdateParams, WorkspaceConfigUpdateResult> WorkspaceConfigUpdate = new("workspace/config/update", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

    public static readonly RpcNotification<WorkspaceConfigChangedParams> WorkspaceConfigChanged = new("workspace/configChanged", RpcDirection.ServerToClient, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", capability: "configChange", notificationOptOut: true);

    public static readonly RpcRequest<WorktreeCreateAndForkParams, WorktreeCreateAndForkResult> WorktreeCreateAndFork = new("worktree/createAndFork", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

    public static readonly RpcRequest<WorktreeCreateAndStartParams, WorktreeCreateAndStartResult> WorktreeCreateAndStart = new("worktree/createAndStart", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

    public static readonly RpcRequest<WorktreeListParams, WorktreeListResult> WorktreeList = new("worktree/list", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

    public static readonly RpcRequest<WorktreeStatusParams, WorktreeStatusResult> WorktreeStatus = new("worktree/status", RpcDirection.ClientToServer, "1", "specs/protocols/appserver-protocol.md", scope: "workspace", errors: CommonErrors);

}
