using DotCraft.Protocol;

namespace DotCraft.CLI.Rendering;

/// <summary>
/// Type of rendering event for agent display
/// </summary>
public enum RenderEventType
{
    /// <summary>
    /// Tool call has started - displays dynamic Status with spinner
    /// </summary>
    ToolCallStarted,
    
    /// <summary>
    /// Tool call has completed - converts Status to static MarkupLine history
    /// </summary>
    ToolCallCompleted,
    
    /// <summary>
    /// Response chunk from AI - displayed in streaming mode
    /// </summary>
    ResponseChunk,
    
    /// <summary>
    /// Thinking/reasoning step reported by agent
    /// </summary>
    ThinkingStep,
    
    /// <summary>
    /// Warning message
    /// </summary>
    Warning,
    
    /// <summary>
    /// Error message
    /// </summary>
    Error,
    
    /// <summary>
    /// Stream/query completed
    /// </summary>
    Complete,
    
    /// <summary>
    /// Approval prompt requested - pause rendering
    /// </summary>
    ApprovalRequired,
    
    /// <summary>
    /// Approval prompt completed - resume rendering
    /// </summary>
    ApprovalCompleted,

    Usage,

    /// <summary>
    /// Debug/diagnostic message — dim grey, buffered during Status spinner sessions
    /// </summary>
    Debug,

    /// <summary>
    /// Agent stream has started — triggers the thinking spinner while waiting for the first response
    /// </summary>
    StreamStarted,

    /// <summary>
    /// SubAgent progress snapshot — periodic aggregated progress data for all active SubAgents.
    /// Emitted by the server-side SubAgentProgressAggregator and relayed via wire notifications.
    /// </summary>
    SubAgentProgress,

    /// <summary>
    /// Incremental token usage delta — emitted each time the agent completes an LLM iteration.
    /// Carries input/output token deltas in Content as "inputTokens,outputTokens".
    /// Used to update a local TokenTracker for real-time spinner display in Wire mode.
    /// </summary>
    UsageDelta,

    /// <summary>
    /// System informational message — a one-line notification about a system-level operation
    /// (e.g., "Context compacted successfully."). Rendered as a dim markup line.
    /// </summary>
    SystemInfo,

    /// <summary>
    /// System status with spinner — a system-level operation in progress
    /// (e.g., "Consolidating memory..."). Rendered as a live Status spinner
    /// that is dismissed when the corresponding completion event arrives.
    /// The <see cref="RenderEvent.Content"/> carries the spinner text,
    /// and <see cref="RenderEvent.AdditionalInfo"/> carries the completion text (if known).
    /// </summary>
    SystemStatus,

    /// <summary>
    /// Plan/todo progress update — emitted when the agent creates or updates a structured plan.
    /// The <see cref="RenderEvent.PlanData"/> carries the complete plan snapshot for rendering.
    /// </summary>
    PlanUpdate
}

/// <summary>
/// Unified rendering event for agent display
/// </summary>
public class RenderEvent
{
    /// <summary>
    /// Type of this rendering event
    /// </summary>
    public RenderEventType Type { get; init; }
    
    /// <summary>
    /// Optional icon emoji for display (e.g., "🔧", "✨", "💭")
    /// </summary>
    public string? Icon { get; init; }
    
    /// <summary>
    /// Optional title for the event (e.g., "Using tool", "Thinking")
    /// </summary>
    public string? Title { get; init; }
    
    /// <summary>
    /// Main content of the event
    /// </summary>
    public string Content { get; init; } = string.Empty;
    
    /// <summary>
    /// Additional information (e.g., tool parameters, result summary)
    /// </summary>
    public string? AdditionalInfo { get; init; }
    
    /// <summary>
    /// Optional color markup for Spectre.Console (e.g., "yellow", "green", "grey")
    /// </summary>
    public string? Color { get; init; }

    /// <summary>
    /// Human-readable formatted description of the tool call.
    /// Generated by <c>ToolRegistry.FormatToolCall</c> in StreamAdapter.
    /// When present, replaces the raw tool name + JSON args in the display.
    /// </summary>
    public string? FormattedDisplay { get; init; }

    /// <summary>
    /// Unique identifier for a tool call, used to correlate
    /// <see cref="RenderEventType.ToolCallStarted"/> with its matching
    /// <see cref="RenderEventType.ToolCallCompleted"/> event (e.g. for parallel SubAgent tracking).
    /// </summary>
    public string? CallId { get; init; }

    /// <summary>
    /// SubAgent progress entries snapshot. Populated only for <see cref="RenderEventType.SubAgentProgress"/> events.
    /// Each entry contains the current tool, token counts, and completion status for a tracked SubAgent.
    /// </summary>
    public IReadOnlyList<SubAgentProgressEntry>? SubAgentEntries { get; init; }

    /// <summary>
    /// Incremental input tokens for <see cref="RenderEventType.UsageDelta"/> events.
    /// </summary>
    public long InputTokensDelta { get; init; }

    /// <summary>
    /// Incremental output tokens for <see cref="RenderEventType.UsageDelta"/> events.
    /// </summary>
    public long OutputTokensDelta { get; init; }

    /// <summary>
    /// Plan/todo data for <see cref="RenderEventType.PlanUpdate"/> events.
    /// Contains the complete plan snapshot including title, overview, and todos.
    /// </summary>
    public PlanUpdateData? PlanData { get; init; }

    /// <summary>
    /// Create a ToolCallStarted event
    /// </summary>
    public static RenderEvent ToolStarted(string? icon, string? title, string content, string? additionalInfo = null, string? formattedDisplay = null, string? callId = null)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ToolCallStarted,
            Icon = icon,
            Title = title,
            Content = content,
            AdditionalInfo = additionalInfo,
            Color = "yellow",
            FormattedDisplay = formattedDisplay,
            CallId = callId
        };
    }

    /// <summary>
    /// Create a ToolCallCompleted event
    /// </summary>
    public static RenderEvent ToolCompleted(string? icon, string? title, string content, string? result = null, string? formattedDisplay = null, string? callId = null)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ToolCallCompleted,
            Icon = icon,
            Title = title,
            Content = content,
            AdditionalInfo = result,
            Color = "grey",
            FormattedDisplay = formattedDisplay,
            CallId = callId
        };
    }

    /// <summary>
    /// Create a ResponseChunk event
    /// </summary>
    public static RenderEvent Response(string content)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ResponseChunk,
            Content = content
        };
    }

    /// <summary>
    /// Create a ThinkingStep event
    /// </summary>
    public static RenderEvent Thinking(string? icon, string? title, string content)
    {
        return new RenderEvent
        {
            Type = RenderEventType.ThinkingStep,
            Icon = icon,
            Title = title,
            Content = content,
            Color = "cyan"
        };
    }

    /// <summary>
    /// Create a Warning event
    /// </summary>
    public static RenderEvent Warn(string message)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Warning,
            Content = message,
            Color = "yellow"
        };
    }

    /// <summary>
    /// Create an Error event
    /// </summary>
    public static RenderEvent ErrorEvent(string message)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Error,
            Content = message,
            Color = "red"
        };
    }

    /// <summary>
    /// Create a Complete event
    /// </summary>
    public static RenderEvent Completed(string message)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Complete,
            Content = message,
            Color = "green"
        };
    }

    /// <summary>
    /// Create an ApprovalRequired event
    /// </summary>
    public static RenderEvent ApprovalRequest()
    {
        return new RenderEvent
        {
            Type = RenderEventType.ApprovalRequired
        };
    }

    /// <summary>
    /// Create an ApprovalCompleted event
    /// </summary>
    public static RenderEvent ApprovalComplete()
    {
        return new RenderEvent
        {
            Type = RenderEventType.ApprovalCompleted
        };
    }

    /// <summary>
    /// Create a Debug diagnostic message event
    /// </summary>
    public static RenderEvent DebugMessage(string message) => new()
    {
        Type = RenderEventType.Debug,
        Content = message,
        Color = "grey"
    };

    public static RenderEvent TokenUsage(long inputTokens, long outputTokens, long totalTokens)
    {
        return new RenderEvent
        {
            Type = RenderEventType.Usage,
            Content = $"{inputTokens},{outputTokens},{totalTokens}",
            Color = "grey"
        };
    }

    /// <summary>
    /// Create a StreamStarted event that triggers the thinking spinner
    /// </summary>
    public static RenderEvent StreamStart() => new()
    {
        Type = RenderEventType.StreamStarted,
        Icon = "💭",
        Title = "Thinking"
    };

    /// <summary>
    /// Create a SubAgentProgress event carrying a snapshot of all active SubAgent entries.
    /// </summary>
    public static RenderEvent SubAgentProgressUpdate(IReadOnlyList<SubAgentProgressEntry> entries) => new()
    {
        Type = RenderEventType.SubAgentProgress,
        SubAgentEntries = entries
    };

    /// <summary>
    /// Create a UsageDelta event carrying incremental token consumption from a single LLM iteration.
    /// </summary>
    public static RenderEvent UsageDeltaEvent(long inputTokens, long outputTokens) => new()
    {
        Type = RenderEventType.UsageDelta,
        InputTokensDelta = inputTokens,
        OutputTokensDelta = outputTokens
    };

    /// <summary>
    /// Create a SystemInfo event — a one-line informational message about a system operation.
    /// </summary>
    public static RenderEvent SystemInfoEvent(string message) => new()
    {
        Type = RenderEventType.SystemInfo,
        Content = message,
        Color = "dim"
    };

    /// <summary>
    /// Create a SystemStatus event — triggers a spinner for an in-progress system operation.
    /// Use <paramref name="completedMessage"/> to indicate the text to show when the operation completes.
    /// </summary>
    public static RenderEvent SystemStatusEvent(string spinnerText, string? completedMessage = null) => new()
    {
        Type = RenderEventType.SystemStatus,
        Content = spinnerText,
        AdditionalInfo = completedMessage,
        Color = "cyan"
    };

    /// <summary>
    /// Create a PlanUpdate event carrying a complete plan snapshot for Todolist rendering.
    /// </summary>
    public static RenderEvent PlanUpdateEvent(PlanUpdateData planData) => new()
    {
        Type = RenderEventType.PlanUpdate,
        PlanData = planData
    };
}

/// <summary>
/// Wire-friendly plan data carried by <see cref="RenderEventType.PlanUpdate"/> events.
/// </summary>
public sealed class PlanUpdateData
{
    public string Title { get; init; } = "";
    public string Overview { get; init; } = "";
    public IReadOnlyList<PlanTodoData> Todos { get; init; } = [];
}

/// <summary>
/// Wire-friendly plan todo entry.
/// </summary>
public sealed class PlanTodoData
{
    public string Id { get; init; } = "";
    public string Content { get; init; } = "";
    public string Priority { get; init; } = "medium";
    public string Status { get; init; } = "pending";
}

