/**
 * @dotcraft/sdk — high-level TypeScript SDK for DotCraft.
 */

export {
  APP_BINDING_ERROR_CODES,
  appBindingToolError,
  appBindingUnavailableError,
  parseAppBindingHandoff,
  DotCraft,
  DotCraftThread,
} from "./dotcraft.js";
export type {
  ApprovalDecision,
  ApprovalHandler,
  AppBindingKind,
  AppBindingErrorCode,
  AppBindingManager,
  AppBindingRequestGetResult,
  AppBindingRequestCreateResult,
  AppSocialBindingResolveParams,
  AppSocialBindingResolveResult,
  AppSurface,
  AppSurfacePublishParams,
  AppSurfaceResolveParams,
  AppConnectionStartResult,
  AppConnectionConnectResult,
  AppPrincipal,
  AppConnectionStatus,
  AppHandoff,
  AppThreadInputEnqueueResult,
  ParsedAppBindingHandoff,
  AppInfo,
  DotCraftCapabilityOptions,
  DotCraftLocalChatOptions,
  DotCraftLocalOptions,
  DotCraftRemoteOptions,
  DotCraftRunEvent,
  DotCraftRunEventBase,
  DotCraftRunResult,
  ModelInfo,
  ModelManager,
  McpRuntimeManager,
  McpServerElicitationRequest,
  McpServerElicitationResponse,
  McpServerOAuthLoginCompletedNotification,
  McpServerOAuthLoginParams,
  McpServerOAuthLoginResult,
  McpServerOrigin,
  McpServerOriginKind,
  McpServerReloadResult,
  McpServerResourceReadParams,
  McpServerResourceReadResult,
  McpServerRuntimeStatus,
  McpServerStartupStatusUpdatedNotification,
  McpServerStatusListParams,
  McpServerStatusListResult,
  McpServerToolCallParams,
  McpServerToolCallResult,
  DynamicToolBinding,
  DynamicToolCallRequest,
  DynamicToolCallResult,
  DynamicToolContentItem,
  DynamicToolFunctionBinding,
  DynamicToolFunctionSpec,
  DynamicToolHandler,
  DynamicToolNamespaceBinding,
  DynamicToolNamespaceSpec,
  DynamicToolSpec,
  EnqueueOptions,
  GetOrCreateThreadOptions,
  InputPart,
  ListThreadOptions,
  QueuedInputResult,
  ReadThreadOptions,
  ResumeThreadOptions,
  RunInput,
  RunOptions,
  RuntimeAdditionalContextEntry,
  SenderContext,
  SessionIdentity,
  SocialBindingIntent,
  SocialBindingTargetSelection,
  SocialChannelBoundBy,
  SocialChannelTarget,
  StartThreadOptions,
  SubscribeOptions,
  ThreadManager,
  ThreadAppBinding,
  ThreadAppBindingSummary,
  ThreadSubscription,
  UserInputHandler,
} from "./dotcraft.js";
export {
  ApprovalTimeoutError,
  DotCraftError,
  DotCraftSdkError,
  InitializationError,
  ThreadNotActiveError,
  ThreadNotFoundError,
  TurnCancelledError,
  TurnFailedError,
  TurnInProgressError,
} from "./errors.js";
export { HubClientError } from "./hubClient.js";
export {
  DECISION_ACCEPT,
  DECISION_ACCEPT_ALWAYS,
  DECISION_ACCEPT_FOR_SESSION,
  DECISION_CANCEL,
  DECISION_DECLINE,
  commandRefPart,
  fileRefPart,
  imageUrlPart,
  localImagePart,
  skillRefPart,
  textPart,
} from "./models.js";
export type { Unsubscribe } from "./client.js";

export const version = "0.2.1";
export const sdkContractVersion = "1.0.0";
