<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DotCraft.DynamicWorkflows</AssemblyName>
    <RootNamespace>DotCraft.DynamicWorkflows</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Jint" Version="4.15.3" />
    <PackageReference Include="JsonSchema.Net" Version="7.3.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotCraft.Core\DotCraft.Core.csproj" />
    <ProjectReference Include="..\DotCraft.Generators\DotCraft.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DotCraft.DynamicWorkflows.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
