# Generated by DotCraft.ProtocolGen. Do not edit.
from typing import Any

from pydantic import BaseModel

from .models_generated import AgentMessagePayload, ApprovalRequestPayload, ApprovalResponsePayload, CommandExecutionPayload, DynamicToolCallPayload, ErrorPayload, ImageGenerationPayload, McpToolCallPayload, ReasoningContentPayload, SystemNoticePayload, ToolCallPayload, ToolExecutionPayload, ToolResultPayload, UserInputRequestPayload, UserInputResponsePayload, UserMessagePayload


SESSION_ITEM_PAYLOAD_MODELS: dict[str, type[BaseModel]] = {
    "agentMessage": AgentMessagePayload,
    "approvalRequest": ApprovalRequestPayload,
    "approvalResponse": ApprovalResponsePayload,
    "commandExecution": CommandExecutionPayload,
    "dynamicToolCall": DynamicToolCallPayload,
    "error": ErrorPayload,
    "imageGeneration": ImageGenerationPayload,
    "mcpToolCall": McpToolCallPayload,
    "reasoningContent": ReasoningContentPayload,
    "systemNotice": SystemNoticePayload,
    "toolCall": ToolCallPayload,
    "toolExecution": ToolExecutionPayload,
    "toolResult": ToolResultPayload,
    "userInputRequest": UserInputRequestPayload,
    "userInputResponse": UserInputResponsePayload,
    "userMessage": UserMessagePayload,
}


def parse_session_item_payload(payload_kind: str | None, payload: Any) -> BaseModel | Any:
    model = SESSION_ITEM_PAYLOAD_MODELS.get(payload_kind) if payload_kind is not None else None
    return payload if model is None or payload is None else model.model_validate(payload)
