# Generated by DotCraft.ProtocolGen. Do not edit.
from typing import Any

from pydantic import BaseModel

from .models_generated import AcpFsReadTextFileParams, AcpFsReadTextFileResult, AcpFsWriteTextFileParams, AcpFsWriteTextFileResult, AcpTerminalCreateParams, AcpTerminalCreateResult, AcpTerminalGetOutputParams, AcpTerminalKillParams, AcpTerminalOutputResult, AcpTerminalReleaseParams, AcpTerminalWaitForExitParams, AppBindingRequestedNotification, AppConnectionChangedNotification, AppListUpdatedNotification, ApprovalRequestParams, ApprovalResponseResult, AuthOpenAiAuthorizeUrlNotification, AuthOpenAiUsageResult, AutomationTaskUpdatedNotification, CronStateChangedNotification, DynamicToolCallParams, DynamicToolCallResult, ExtChannelSendParams, ExtChannelSendResult, ExtChannelToolCallParams, ExtChannelToolCallResult, ItemDeltaNotification, ItemNotification, McpAppViewStatusUpdatedParams, McpServerElicitationRequestParams, McpServerElicitationResponse, McpServerOAuthLoginCompletedNotification, McpServerStartupStatusUpdatedNotification, NodeReplCancelParams, NodeReplEvaluateParams, NodeReplEvaluateResult, PlanUpdatedNotification, RpcEmpty, SubAgentGraphChangedNotification, SubAgentProgressNotification, SystemEventNotification, SystemJobResultNotification, TeamsTeamChangedNotification, TerminalLifecycleNotification, ThreadAppBindingsChangedNotification, ThreadDeletedNotification, ThreadGoalClearedNotification, ThreadGoalUpdatedNotification, ThreadNotification, ThreadQueueUpdatedNotification, ThreadRenamedNotification, ThreadRuntimeChangedParams, ThreadStatusChangedNotification, TurnNotification, UiResourceReadParams, UiResourceReadResult, UsageDeltaNotification, UserInputRequestParams, UserInputResponseResult, WorkflowRunUpdatedNotification, WorkspaceConfigChangedParams


SERVER_NOTIFICATION_MODELS: dict[str, type[BaseModel]] = {
    "app/binding/requested": AppBindingRequestedNotification,
    "app/connection/changed": AppConnectionChangedNotification,
    "app/list/updated": AppListUpdatedNotification,
    "auth/openai/authorizeUrl": AuthOpenAiAuthorizeUrlNotification,
    "auth/openai/usageChanged": AuthOpenAiUsageResult,
    "automation/task/updated": AutomationTaskUpdatedNotification,
    "cron/stateChanged": CronStateChangedNotification,
    "item/agentMessage/delta": ItemDeltaNotification,
    "item/approval/resolved": ItemNotification,
    "item/commandExecution/outputDelta": ItemDeltaNotification,
    "item/completed": ItemNotification,
    "item/reasoning/delta": ItemDeltaNotification,
    "item/started": ItemNotification,
    "item/tool/requestUserInput/resolved": ItemNotification,
    "item/toolCall/argumentsDelta": ItemDeltaNotification,
    "item/usage/delta": UsageDeltaNotification,
    "mcpApp/view/status/updated": McpAppViewStatusUpdatedParams,
    "mcpServer/oauthLogin/completed": McpServerOAuthLoginCompletedNotification,
    "mcpServer/startupStatus/updated": McpServerStartupStatusUpdatedNotification,
    "plan/updated": PlanUpdatedNotification,
    "subagent/graphChanged": SubAgentGraphChangedNotification,
    "subagent/progress": SubAgentProgressNotification,
    "system/event": SystemEventNotification,
    "system/jobResult": SystemJobResultNotification,
    "teams/team/changed": TeamsTeamChangedNotification,
    "terminal/cleaned": TerminalLifecycleNotification,
    "terminal/completed": TerminalLifecycleNotification,
    "terminal/outputDelta": TerminalLifecycleNotification,
    "terminal/stalled": TerminalLifecycleNotification,
    "terminal/started": TerminalLifecycleNotification,
    "thread/appBindings/changed": ThreadAppBindingsChangedNotification,
    "thread/deleted": ThreadDeletedNotification,
    "thread/goal/cleared": ThreadGoalClearedNotification,
    "thread/goal/updated": ThreadGoalUpdatedNotification,
    "thread/queue/updated": ThreadQueueUpdatedNotification,
    "thread/renamed": ThreadRenamedNotification,
    "thread/resumed": ThreadNotification,
    "thread/runtimeChanged": ThreadRuntimeChangedParams,
    "thread/started": ThreadNotification,
    "thread/statusChanged": ThreadStatusChangedNotification,
    "thread/updated": ThreadNotification,
    "turn/cancelled": TurnNotification,
    "turn/completed": TurnNotification,
    "turn/failed": TurnNotification,
    "turn/started": TurnNotification,
    "workflow/run/updated": WorkflowRunUpdatedNotification,
    "workspace/configChanged": WorkspaceConfigChangedParams,
}

SERVER_REQUEST_MODELS: dict[str, tuple[type[BaseModel], type[BaseModel]]] = {
    "ext/acp/fs/readTextFile": (AcpFsReadTextFileParams, AcpFsReadTextFileResult),
    "ext/acp/fs/writeTextFile": (AcpFsWriteTextFileParams, AcpFsWriteTextFileResult),
    "ext/acp/terminal/create": (AcpTerminalCreateParams, AcpTerminalCreateResult),
    "ext/acp/terminal/getOutput": (AcpTerminalGetOutputParams, AcpTerminalOutputResult),
    "ext/acp/terminal/kill": (AcpTerminalKillParams, RpcEmpty),
    "ext/acp/terminal/release": (AcpTerminalReleaseParams, RpcEmpty),
    "ext/acp/terminal/waitForExit": (AcpTerminalWaitForExitParams, AcpTerminalOutputResult),
    "ext/channel/heartbeat": (RpcEmpty, RpcEmpty),
    "ext/channel/send": (ExtChannelSendParams, ExtChannelSendResult),
    "ext/channel/toolCall": (ExtChannelToolCallParams, ExtChannelToolCallResult),
    "ext/nodeRepl/cancel": (NodeReplCancelParams, RpcEmpty),
    "ext/nodeRepl/evaluate": (NodeReplEvaluateParams, NodeReplEvaluateResult),
    "item/approval/request": (ApprovalRequestParams, ApprovalResponseResult),
    "item/resource/read": (UiResourceReadParams, UiResourceReadResult),
    "item/tool/call": (DynamicToolCallParams, DynamicToolCallResult),
    "item/tool/requestUserInput": (UserInputRequestParams, UserInputResponseResult),
    "mcpServer/elicitation/request": (McpServerElicitationRequestParams, McpServerElicitationResponse),
}


def parse_server_notification(method: str, params: dict[str, Any]) -> BaseModel | dict[str, Any]:
    model = SERVER_NOTIFICATION_MODELS.get(method)
    return params if model is None else model.model_validate(params)


def parse_server_request(method: str, params: dict[str, Any]) -> BaseModel | dict[str, Any]:
    models = SERVER_REQUEST_MODELS.get(method)
    return params if models is None else models[0].model_validate(params)
