import { itemOf, items, rarities, seriesIds, slots, type Item, type ItemId, type Rarity, type Series, type Slot } from './items.js'

export interface DecorationCopy {
  name: string
  feature: string
  colors: readonly string[]
  mount: string
}
export type Decoration = Item & DecorationCopy

export const slotLabels: Record<Slot, string> = { head: 'Head', face: 'Face', hand: 'Hand', back: 'Back', skin: 'Skin' }
export const rarityMeta: Record<Rarity, { label: string; color: string }> = {
  common: { label: 'Common', color: '#8a94a6' },
  uncommon: { label: 'Uncommon', color: '#3f9d5b' },
  rare: { label: 'Rare', color: '#3b7be8' },
  epic: { label: 'Epic', color: '#8b5cf6' },
  legendary: { label: 'Legendary', color: '#e0962c' },
}
export const seriesLabels: Record<Series, string> = {
  everyday: 'Everyday', dev: 'Dev culture', tech: 'Tech & cyber', fantasy: 'Fantasy', nature: 'Nature', snack: 'Snack', critters: 'Critters',
}

const held = 'Screen-left hand; shares the arm pivot, stows for laptop and question sign, then restores'
const copy: Record<ItemId, DecorationCopy> = {
  'baseball-cap': { name: 'Baseball cap', feature: 'Rounded crown with a short right-facing brim', colors: ['#e87967', '#b94f50', '#f5a18c'], mount: 'Crown overlaps the top edge; the brim stays inside the body' },
  'bucket-hat': { name: 'Bucket hat', feature: 'Flat top with a continuous downward brim', colors: ['#94bda6', '#5b887a', '#bed8c1'], mount: 'Brim follows the top edge with a slight center overlap' },
  beret: { name: 'Beret', feature: 'Soft left-leaning crown with a short stem', colors: ['#b17498', '#784c71', '#cf9db5'], mount: 'Narrow band rests on top; the crown leans left' },
  beanie: { name: 'Beanie', feature: 'Rounded crown and wide folded cuff with minimal texture', colors: ['#e9a653', '#bc753d', '#f7c676'], mount: 'Folded cuff sits on the top edge; crown stays centered' },
  'top-hat': { name: 'Top hat', feature: 'Tall crown, narrow brim, and burgundy band', colors: ['#465069', '#293247', '#c96e85'], mount: 'Narrow brim rests flat on top; crown tapers at its base' },
  'wizard-hat': { name: 'Wizard hat', feature: 'Curved point, wide brim, and gold star', colors: ['#8773c1', '#594b93', '#f4cc75'], mount: 'Wide brim rests on top; point curves into the center safe area' },
  'chef-hat': { name: 'Chef hat', feature: 'Three-lobed puff with an upright band', colors: ['#f5eee3', '#d7caba', '#fffaf1'], mount: 'Band rests at the center of the top edge' },
  'party-hat': { name: 'Party hat', feature: 'Cone with two colored bands and a pom-pom', colors: ['#ea9baf', '#8075b7', '#f5d07b'], mount: 'Shallow curved base follows the top of the body' },
  crown: { name: 'Crown', feature: 'Three rounded points with a central sapphire', colors: ['#efc65c', '#c99139', '#73b8cc'], mount: 'Curved gold band wraps the top edge; all points face up' },
  'hard-hat': { name: 'Hard hat', feature: 'Rounded shell, center ridge, and short front brim', colors: ['#f5bd48', '#d68d32', '#ffdc79'], mount: 'Short brim overlaps the top edge; ridge stays centered' },
  nightcap: { name: 'Nightcap', feature: 'Soft drooping point with a pom-pom', colors: ['#789cc9', '#4c709f', '#dce8f4'], mount: 'Soft band follows the top edge; pom-pom stays upper right' },
  'straw-hat': { name: 'Straw hat', feature: 'Low round crown, wide oval brim, and red band', colors: ['#e8c78a', '#c49b5e', '#c57568'], mount: 'Wide brim rests flat without entering the arm areas' },
  poop: { name: 'Poop', feature: 'Three rounded layers with a playful curled tip', colors: ['#a97b5f', '#805840', '#c49976'], mount: 'Wide bottom layer rests directly on top; color separates each layer' },
  banana: { name: 'Banana', feature: 'Crescent fruit with stems and an inner color plane', colors: ['#f3cf62', '#dbaa40', '#89705a'], mount: 'Outer curve touches the top; both stems point up' },
  'fried-egg': { name: 'Fried egg', feature: 'Irregular rounded white with a raised golden yolk', colors: ['#fff9e8', '#e6d9bb', '#f3be43'], mount: 'White spreads across the top; raised yolk defines the silhouette' },
  'rubber-duck': { name: 'Rubber duck', feature: 'Round head, flat orange bill, and short raised tail', colors: ['#f6d05e', '#e4ae3e', '#e58b4b'], mount: 'Belly rests flat on top, with bill left and tail right' },
  'paper-boat': { name: 'Paper boat', feature: 'Folded hull with a central triangular plane', colors: ['#d6e7eb', '#92b5c1', '#f1f7f5'], mount: 'Folded hull edge rests on top; main fold stays centered' },
  'traffic-cone': { name: 'Traffic cone', feature: 'Orange cone with a white band and flat base', colors: ['#ed985f', '#c96c43', '#fff0dd'], mount: 'Flat base rests on top; cone tapers upward' },
  sprout: { name: 'Sprout', feature: 'Short stem with two leaves pointing in different directions', colors: ['#89b875', '#537f59', '#b5d38f'], mount: 'Stem grows directly from the top edge without a pot or base' },
  donut: { name: 'Donut', feature: 'Clear center hole, half-ring of icing, and a few sprinkles', colors: ['#dbab70', '#bf8456', '#e5a0b3'], mount: 'Lower curve touches the top; center remains an open cutout' },
  'ringed-planet': { name: 'Ringed planet', feature: 'Banded sand-colored planet inside a tilted pale ring with a soft glow', colors: ['#d9b07a', '#b8875a', '#f1e3c8'], mount: 'Ring underside touches the top edge; the planet floats above the center' },
  'cat-ears': { name: 'Cat ears', feature: 'Two tan triangular ears with pink inner planes', colors: ['#c9a27e', '#f2a0b4'], mount: 'Ears rise from the top corners; nothing sits between them' },
  'cowboy-hat': { name: 'Cowboy hat', feature: 'Tall creased crown over a wide curved brim with a dark band', colors: ['#b98352', '#a8734a', '#6e4a2e'], mount: 'Brim rests across the top edge and stays clear of the arms' },
  mushroom: { name: 'Mushroom', feature: 'Red cap with cream spots on a short cream stem', colors: ['#e8654f', '#fff4ef', '#fff1dc'], mount: 'Stem stands on the top edge; the cap overhangs both sides' },
  'shark-fin': { name: 'Shark fin', feature: 'Gray dorsal fin with a lighter leading plane', colors: ['#8b95a5', '#a7b1c0'], mount: 'Fin base spans the top edge center' },
  'propeller-cap': { name: 'Propeller cap', feature: 'Yellow and red cap dome with a spinning propeller on a button', colors: ['#f6b500', '#e8654f', '#c9d2ff'], mount: 'Dome overlaps the top edge; the propeller spins flat at full size' },
  'graduation-cap': { name: 'Graduation cap', feature: 'Black mortarboard with a gold button and a swinging tassel', colors: ['#2b2f3a', '#3c4658', '#f6b500'], mount: 'Skull cap rests on the top edge; the board floats above it' },
  'ice-cream': { name: 'Ice cream', feature: 'Strawberry scoop with an upright cone and a cherry', colors: ['#f2a0b4', '#e0ad84', '#e8654f'], mount: 'Scoop rests on the top edge; the cone points up' },
  'floppy-disk': { name: 'Floppy disk', feature: 'Navy disk with a silver shutter and a white label', colors: ['#3c4658', '#a7b1c0', '#ffffff'], mount: 'Tilted disk stands half-inserted in the top edge, shutter up' },
  'flower-crown': { name: 'Flower crown', feature: 'Green wreath with alternating pink and yellow blossoms', colors: ['#89b875', '#f2a0b4', '#f6b500'], mount: 'Wreath follows the top edge without a brim' },
  'pirate-hat': { name: 'Pirate hat', feature: 'Black tricorn with an upturned brim and a white skull mark', colors: ['#2b2f3a', '#3c4658', '#ffffff'], mount: 'Brim rests on the top edge; points stay clear of the arms' },
  rocket: { name: 'Rocket', feature: 'Pale rocket with a red nose, red fins and a flickering flame', colors: ['#dce8f4', '#e8654f', '#ffb347'], mount: 'Fins rest on the top edge; the flame burns between them' },
  lightning: { name: 'Lightning', feature: 'Yellow bolt standing upright with a breathing glow', colors: ['#ffcf11', '#fff3c4'], mount: 'Lower tip touches the top edge center' },
  'crystal-cluster': { name: 'Crystal cluster', feature: 'Three violet crystals with a lighter facet and a breathing glow', colors: ['#8b5cf6', '#a78bfa', '#c4b5fd'], mount: 'Crystal bases sit on the top edge' },
  ufo: { name: 'UFO', feature: 'Hovering saucer with a glass dome, blinking lights and a tractor beam', colors: ['#8b95a5', '#a2c5d1', '#c7f6ff'], mount: 'Saucer floats above the head; the beam lands on the top edge' },
  'mini-volcano': { name: 'Mini volcano', feature: 'Dark rock cone with a glowing lava crater and rising smoke', colors: ['#564545', '#e8451f', '#ffb347'], mount: 'Wide base rests flat on the top edge; smoke rises from the crater' },
  'phoenix-perch': { name: 'Phoenix', feature: 'Orange firebird with a flickering flame crest and flame tail', colors: ['#ee6a2c', '#c2412a', '#ffb02e'], mount: 'Talons grip the top edge; the tail rises clear of both arms' },
  'satellite-dish': { name: 'Satellite dish', feature: 'Tilted gray dish with a yellow feed on a short mast', colors: ['#8b95a5', '#dce8f4', '#f6b500'], mount: 'Mast foot bolts to the top edge center, where the antenna stood' },
  'cursor-arrow': { name: 'Cursor arrow', feature: 'Giant black pointer with a white border, clicking the head', colors: ['#2b2f3a', '#5b6577', '#ffffff'], mount: 'Tip touches the top edge; the tail rises to the upper right' },
  'viking-helmet': { name: 'Viking helmet', feature: 'Steel dome with a tan band and two curved ivory horns', colors: ['#a7b1c0', '#c49b5e', '#fff1dc'], mount: 'Band sits on the top edge; the horns stay within the widest brim' },
  'wind-up-key': { name: 'Wind-up key', feature: 'Brass toy key whose two round bows slowly turn', colors: ['#efc65c', '#c99139'], mount: 'Shaft plugs into the top edge center' },
  crab: { name: 'Crab', feature: 'Red crab with both pincers raised and snapping', colors: ['#e8654f', '#c24a3a', '#fff4ef'], mount: 'Four legs hook over the top edge; the pincers stay clear of both arms' },
  cupcake: { name: 'Cupcake', feature: 'Pink swirl cupcake in a teal cup with one lit candle', colors: ['#f2a0b4', '#7fc7d9', '#ffb347'], mount: 'Flat cup base rests on the top edge' },
  gears: { name: 'Gears', feature: 'Two meshed steel cogs turning against each other', colors: ['#8b95a5', '#a7b1c0', '#f6b500'], mount: 'Both cogs stand on the top edge and mesh above its center' },
  'rain-cloud': { name: 'Rain cloud', feature: 'Gray storm cloud raining in three blue columns', colors: ['#9aa6b8', '#dfe5ee', '#4f7cf6'], mount: 'Cloud floats above the head; the rain lands on the top edge' },
  'maneki-neko': { name: 'Maneki-neko', feature: 'Gold beckoning cat with a red collar, sheen and warm glow', colors: ['#efc65c', '#e8654f', '#fff3c4'], mount: 'Base sits on the top edge center; the raised paw stays clear of the arms' },

  shades: { name: 'Shades', feature: 'Two dark lenses with a short bridge pushed up on the brow', colors: ['#2b2f3a', '#6b7280'], mount: 'Fits within the forehead band above the screen' },
  headlamp: { name: 'Headlamp', feature: 'Round yellow lamp with a gray bezel on a dark strap', colors: ['#3c4658', '#8b95a5', '#ffd970'], mount: 'Lamp centers in the forehead band; the strap spans the brow' },
  'forehead-goggles': { name: 'Forehead goggles', feature: 'Two blue-gray lenses with a center bridge', colors: ['#8b7568', '#a2c5d1', '#dec8ae'], mount: 'Fits within the forehead band; bridge anchors above the screen' },
  'heart-glasses': { name: 'Heart glasses', feature: 'Pink heart lenses with a short bridge pushed up on the brow', colors: ['#c9577a', '#f2a0b4'], mount: 'Fits within the forehead band above the screen' },
  'snorkel-mask': { name: 'Snorkel mask', feature: 'Wide cyan mask pushed up with an orange snorkel tube', colors: ['#a2c5d1', '#3c4658', '#ed985f'], mount: 'Mask fits the forehead band; the tube rises at the screen-right temple and stows for the question sign' },
  'bow-tie': { name: 'Bow tie', feature: 'Red bow tie with two flared wings and a round knot', colors: ['#e8654f', '#b94f50'], mount: 'Knot centers on the chin below the screen; the wings overhang the base' },
  neckerchief: { name: 'Neckerchief', feature: 'Yellow triangle scarf with a rolled band, point down', colors: ['#dbaa40', '#f3cf62'], mount: 'Band follows the chin below the screen; the point hangs over the base' },
  'ear-pencil': { name: 'Ear pencil', feature: 'Yellow pencil tucked at an angle with the pink eraser up', colors: ['#f3cf62', '#e0ad84', '#f2a0b4'], mount: 'Rests at the screen-right temple; stows while the arm holds the question sign' },
  'bell-collar': { name: 'Bell collar', feature: 'Red collar with a round gold bell at the front', colors: ['#e8654f', '#f6b500', '#805840'], mount: 'Collar follows the chin below the screen; the bell hangs over the base' },
  'watermelon-glasses': { name: 'Watermelon glasses', feature: 'Two half-moon watermelon lenses with green rinds down and dark seeds', colors: ['#e8654f', '#4fae6a', '#2b2f3a'], mount: 'Fits within the forehead band above the screen' },
  'star-glasses': { name: 'Star glasses', feature: 'Two gold star lenses with a short bridge; one lens glints', colors: ['#f6b500', '#fff3c4'], mount: 'Fits within the forehead band above the screen' },
  'sticky-note': { name: 'Sticky note', feature: 'Yellow square note with one curled corner', colors: ['#f6d365', '#e8b93a'], mount: 'Stuck flat on the screen-right temple corner at a slight tilt; stows while the arm holds the question sign' },
  'lanyard-badge': { name: 'Lanyard badge', feature: 'Conference badge with a role-color header on a yellow lanyard', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: 'Lanyard runs along the chin below the screen; the badge hangs over the base' },
  'prize-rosette': { name: 'Prize rosette', feature: 'Blue pleated rosette with a gold center and two notched ribbon tails', colors: ['#4f7cf6', '#3161f7', '#f6b500'], mount: 'Pinned at the chin center below the screen; the tails hang over the base' },
  'cherry-charm': { name: 'Cherry charm', feature: 'Two red cherries on a green V stem with a leaf', colors: ['#e8654f', '#b94f50', '#89b875'], mount: 'Stem hooks over the screen-right temple corner; stows while the arm holds the question sign' },
  songbird: { name: 'Songbird', feature: 'Round bluebird with an orange breast and a bobbing head', colors: ['#4f7cf6', '#ed985f', '#2b2f3a'], mount: 'Perches on the screen-right temple corner; stows while the arm holds the question sign' },
  amulet: { name: 'Amulet', feature: 'Dark cord with a glowing teal teardrop crystal', colors: ['#3c4658', '#5eead4', '#ccfbf1'], mount: 'Cord follows the chin below the screen; the crystal hangs over the base' },
  'mecha-faceplate': { name: 'Mecha faceplate', feature: 'White face armor with a dark visor band, angular yellow-green eyes, a red chin plate and two vents', colors: ['#f4f6fb', '#1d2433', '#d94a3a'], mount: 'Replaces the face inside the white screen frame; the eyes change light, not shape' },
  'pixel-screen': { name: 'Pixel screen', feature: 'Dark monitor with phosphor-green pixel eyes: blocks, a blocky smile, a loading bar and dim dashes', colors: ['#1f2a3a', '#7dff8a'], mount: 'Replaces the face inside the white screen frame; pixel glyphs carry all four expressions' },
  'segment-display': { name: 'Segment display', feature: 'Olive LCD with two seven-segment digit eyes', colors: ['#b7c49a', '#2f3a2b'], mount: 'Replaces the face inside the white screen frame; lit segments carry all four expressions' },
  'knight-visor': { name: 'Knight visor', feature: 'Steel great-helm plate with a T-shaped slit and ember eyes', colors: ['#a7b1c0', '#1d2433', '#ffb547'], mount: 'Replaces the face inside the white screen frame; light carries all four expressions' },
  'gold-faceplate': { name: 'Gold faceplate', feature: 'Armored gold plate whose fixed eye slits change light, not shape: cyan idle, warm flare, amber scan, dim ember', colors: ['#efc04a', '#bf8a2a', '#6fdcff'], mount: 'Replaces the face inside the white screen frame; light carries all four expressions' },
  'porthole-helmet': { name: 'Porthole helmet', feature: 'Copper diving helmet with a round porthole, LED eyes and rising bubbles', colors: ['#c47a4a', '#1f4a5a', '#c7f6ff'], mount: 'Replaces the face inside the white screen frame; the LED pair carries all four expressions' },
  'neon-visor': { name: 'Neon visor', feature: 'Full smoked visor with a pair of LED eyes that lid, squint and rest, plus a passing scan line', colors: ['#1d2433', '#4de3ff', '#c7f6ff'], mount: 'Replaces the face inside the white screen frame; the LED pair carries all four expressions' },
  'dragon-visor': { name: 'Dragon visor', feature: 'Dark scaled plate with slit-pupil eyes that smolder, flare, scan and dim', colors: ['#1f2b2c', '#2f4543', '#ffb547'], mount: 'Replaces the face inside the white screen frame; light carries all four expressions' },
  'code-rain': { name: 'Code rain', feature: 'Black screen of falling green code behind a pair of LED eyes', colors: ['#0b1410', '#7dff8a', '#d9ffe0'], mount: 'Replaces the face inside the white screen frame; the LED pair carries all four expressions' },

  'task-board': { name: 'Task board', feature: 'White planning board with connected role-color markers and a yellow accent', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  wrench: { name: 'Wrench', feature: 'White open-ended wrench with role-color outlines and a yellow handle inset', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  'coffee-mug': { name: 'Coffee mug', feature: 'White mug with a role-color band and rising steam', colors: ['#ffffff', '#3161f7', '#5a3c2a'], mount: held },
  shield: { name: 'Shield', feature: 'White shield with a role-color outline and upright check', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  magnifier: { name: 'Magnifier', feature: 'Upright white lens frame with a role-color outline and a lower grip', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  'control-panel': { name: 'Control panel', feature: 'White control panel with dark rails and role-color and yellow knobs', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  'magic-wand': { name: 'Magic wand', feature: 'Dark wand tipped with a gold star and drifting sparkles', colors: ['#3b2f5c', '#f6b500', '#fff3c4'], mount: held },
  'energy-blade': { name: 'Energy blade', feature: 'Compact hilt with a blade that cycles cyan, magenta and green while it extends and retracts', colors: ['#2a3140', '#4de3ff', '#e6fbff'], mount: `${held}; the blade rises beside the body, never across the screen` },
  'thunder-hammer': { name: 'Thunder hammer', feature: 'Steel hammer with a role-color band and crackling lightning arcs', colors: ['#aab4c3', '#3161f7', '#4de3ff'], mount: `${held}; the head rises beside the body, never across the screen` },
  paintbrush: { name: 'Paintbrush', feature: 'Wooden brush with a steel ferrule and a role-color paint tip', colors: ['#e0ad84', '#8b95a5', '#3161f7'], mount: held },
  'boba-tea': { name: 'Boba tea', feature: 'White cup of milk tea with dark pearls and a yellow straw', colors: ['#ffffff', '#e0ad84', '#3c4658'], mount: held },
  gamepad: { name: 'Gamepad', feature: 'White controller with a role-color d-pad and two buttons', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  flag: { name: 'Flag', feature: 'Steel pole with a waving role-color pennant', colors: ['#8b95a5', '#3161f7'], mount: `${held}; the pennant rises beside the body` },
  lantern: { name: 'Lantern', feature: 'Red paper lantern with dark caps and a warm breathing glow', colors: ['#e8654f', '#3c4658', '#ffd970'], mount: held },
  staff: { name: 'Staff', feature: 'Wooden staff topped with a glowing orb that shifts violet, cyan and pink', colors: ['#8a6520', '#8b5cf6', '#c4b5fd'], mount: `${held}; the orb rises beside the body` },
  umbrella: { name: 'Umbrella', feature: 'Open red umbrella with a scalloped canopy and a hooked handle', colors: ['#e8654f', '#b94f50', '#3c4658'], mount: `${held}; the canopy rises beside the body` },
  'pizza-slice': { name: 'Pizza slice', feature: 'Cheese slice pointing up with a crust and pepperoni dots', colors: ['#f3cf62', '#e0ad84', '#e8654f'], mount: held },
  sunflower: { name: 'Sunflower', feature: 'Scalloped yellow bloom with a brown center on a leafy stem', colors: ['#f6b500', '#805840', '#89b875'], mount: `${held}; the bloom rises beside the body` },
  camera: { name: 'Camera', feature: 'White compact camera with a big role-color lens ring and yellow shutter', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  binoculars: { name: 'Binoculars', feature: 'Two upright green barrels with cyan lenses facing out', colors: ['#537f59', '#3c4658', '#a2c5d1'], mount: held },
  'goldfish-bag': { name: 'Goldfish bag', feature: 'Knotted water bag with an orange goldfish inside', colors: ['#c7f6ff', '#a2c5d1', '#ed985f'], mount: `${held}; the bag hangs below the hand` },
  megaphone: { name: 'Megaphone', feature: 'White cone angled up and out with a role-color rim', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: `${held}; the bell rises beside the body` },
  parrot: { name: 'Parrot', feature: 'Green parrot with a red face and a bobbing head', colors: ['#4fae6a', '#e8654f', '#f6b500'], mount: `${held}; the parrot perches beside the body` },
  'firefly-jar': { name: 'Firefly jar', feature: 'Glass jar with a gray lid and three blinking fireflies', colors: ['#c7f6ff', '#8b95a5', '#d9ff5a'], mount: held },
  trophy: { name: 'Trophy', feature: 'Gold two-handled cup on a dark base with sparkles and a glow', colors: ['#efc65c', '#c99139', '#3c4658'], mount: held },
  'walkie-talkie': { name: 'Walkie-talkie', feature: 'White handset with a stubby antenna, role-color grille and yellow knob', colors: ['#ffffff', '#3161f7', '#f6b500'], mount: held },
  potion: { name: 'Potion', feature: 'Round glass flask of magenta liquid with a cork stopper', colors: ['#e05aa8', '#ffffff', '#c49b5e'], mount: `${held}; the flask hangs below the hand` },
  'genie-lamp': { name: 'Genie lamp', feature: 'Gold oil lamp with a domed lid, curled handle and long spout', colors: ['#efc65c', '#c99139', '#fff3c4'], mount: `${held}; the spout points away from the body` },
  lollipop: { name: 'Lollipop', feature: 'Big pink swirl lollipop on a white stick', colors: ['#f2a0b4', '#e8654f', '#ffffff'], mount: `${held}; the candy rises beside the body` },
  pickaxe: { name: 'Pickaxe', feature: 'Curved steel pick head on a wooden handle with a yellow grip', colors: ['#8b95a5', '#e0ad84', '#f6b500'], mount: `${held}; the head rises beside the body, never across the screen` },
  'bug-net': { name: 'Bug net', feature: 'Role-color hoop net on a pole with a wriggling beetle inside', colors: ['#ffffff', '#3161f7', '#2b2f3a'], mount: `${held}; the hoop rises beside the body` },
  'hot-pepper': { name: 'Hot pepper', feature: 'Red chili with a green cap and a flame at its tip', colors: ['#e8654f', '#4fae6a', '#ffb347'], mount: `${held}; the pepper curves up beside the body` },
  'plasma-globe': { name: 'Plasma globe', feature: 'Dark glass ball on a black base with flickering violet tendrils', colors: ['#1d2433', '#c084fc', '#f5d0fe'], mount: held },
  'master-key': { name: 'Master key', feature: 'Giant golden key, teeth up, with a sweeping sheen and a glow', colors: ['#efc65c', '#c99139', '#fff3c4'], mount: `${held}; the shaft rises beside the body, never across the screen` },
  'pet-dragon': { name: 'Pet dragon', feature: 'Small green dragon flapping its wings and puffing fire outward', colors: ['#4fae6a', '#2f7a4f', '#ffb347'], mount: `${held}; the dragon perches beside the body` },

  cape: { name: 'Cape', feature: 'Crimson cape that flares wide below the body with a lighter lining', colors: ['#b23a48', '#d65a68'], mount: 'Collar sits at the shoulders behind the body; the flares show beside and below the base' },
  'crescent-moon': { name: 'Crescent moon', feature: 'Yellow crescent rising behind the head with a small star', colors: ['#f6d365', '#fff3c4'], mount: 'Moon shows behind the upper-left of the head' },
  kite: { name: 'Kite', feature: 'Red and yellow diamond kite flying on a string', colors: ['#e8654f', '#f6b500', '#8b95a5'], mount: 'Kite flies above the right shoulder; the string meets behind the body' },
  'solar-panels': { name: 'Solar panels', feature: 'Two dark-blue cell panels raised on steel masts', colors: ['#2f4a8a', '#5b7fd6', '#8b95a5'], mount: 'Masts bolt in behind both shoulders; the panels tilt outward above the arms' },
  'power-cord': { name: 'Power cord', feature: 'Dark plug pushed into the body with a coiled cord', colors: ['#3c4658', '#5b6577'], mount: 'Plug seats in the lower-right edge of the base; the cord coils beside it' },
  surfboard: { name: 'Surfboard', feature: 'Long yellow board with a red stripe', colors: ['#f3cf62', '#e8654f'], mount: 'Board leans behind the right side and shows above and below the arm' },
  jetpack: { name: 'Jetpack', feature: 'Two steel tanks with red caps and flickering flames', colors: ['#8b95a5', '#e8654f', '#ffb347'], mount: 'Tanks show beside both arms behind the body; flames flicker below' },
  'star-trail': { name: 'Star trail', feature: 'Three gold four-point stars twinkling beside the body', colors: ['#f6b500', '#fff3c4'], mount: 'Stars float beside the body and twinkle at full size' },
  balloons: { name: 'Balloons', feature: 'Three balloons on strings rising beside the head', colors: ['#e8654f', '#f6b500', '#4f7cf6'], mount: 'Strings meet behind the left shoulder; the bunch bobs at full size' },
  'fox-tail': { name: 'Fox tail', feature: 'Bushy orange tail with a cream tip that sways', colors: ['#ed985f', '#c96c43', '#fff1dc'], mount: 'Root emerges from behind the lower-right edge; the tail curls up beside the arm' },
  'hero-scarf': { name: 'Hero scarf', feature: 'Red scarf whose two forked tails stream and wave', colors: ['#e8654f', '#b94f50'], mount: 'Knot sits behind the left shoulder; the tails stream beside the arm' },
  guitar: { name: 'Guitar', feature: 'Acoustic guitar slung on a strap', colors: ['#e0ad84', '#8b5a2b', '#f6d365'], mount: 'Body shows at the lower left; the neck rises above the right shoulder' },
  'bat-wings': { name: 'Bat wings', feature: 'Two scalloped violet wings with darker membranes that flap', colors: ['#5b3a8c', '#3d2563'], mount: 'Wings spread from behind the shoulders and stay clear of the head' },
  'butterfly-wings': { name: 'Butterfly wings', feature: 'Two pink two-lobed wings with cream inner planes that flap', colors: ['#f2a0b4', '#fff3c4'], mount: 'Wings spread from behind the shoulders' },
  comet: { name: 'Comet', feature: 'Gold comet curling a periwinkle tail around the head, softly glowing', colors: ['#f6b500', '#b9c4ff', '#fff3c4'], mount: 'Head passes the right shoulder; the tail curls in behind the antenna or hat' },
  halo: { name: 'Halo', feature: 'Flat golden aureole centered on the antenna light with a breathing glow', colors: ['#f6b500', '#ffe08a', '#fff7dc'], mount: 'Ring sits behind the light and hats; the light disc covers its center' },
  'angel-wings': { name: 'Angel wings', feature: 'Two white feathered wings with a soft glow and a slow flap', colors: ['#ffffff', '#eef1ff', '#c9d2ff'], mount: 'Wings spread from behind the shoulders' },
  'sun-rays': { name: 'Sun rays', feature: 'Twelve alternating gold rays turning slowly behind the body', colors: ['#f6b500', '#ffcf11'], mount: 'Rays radiate from the body center' },
  'koi-orbit': { name: 'Koi orbit', feature: 'Two orange koi swimming circles in front of and behind the robot', colors: ['#ed985f', '#fff4ef', '#e8654f'], mount: 'Koi circle low around the body; they pass in front below the screen' },
  'orbit-ring': { name: 'Orbit ring', feature: 'Tilted orbit belt with three bodies that circle in front of and behind the robot', colors: ['#b9c4ff', '#f6b500', '#ff9ad9'], mount: 'Belt crosses low around the body; bodies pass in front below the screen' },
  'dragon-wings': { name: 'Dragon wings', feature: 'Two large crimson wings with dark membranes and ember tips that flap', colors: ['#b23a48', '#7f2634', '#ffb347'], mount: 'Wings spread wide from behind the shoulders' },
  'twin-blades': { name: 'Twin blades', feature: 'Black and pale teal swords crossed, edges glowing with a sheen', colors: ['#1f2330', '#8fdccf', '#9fb2ff'], mount: 'Hilts rise from clasps above both shoulders; the blades cross behind and the tips show below the lower corners' },
  'peeking-cat': { name: 'Peeking cat', feature: 'Orange tabby head with pointed ears peering over the shoulder', colors: ['#ed985f', '#c96c43', '#fff1dc'], mount: 'Head rises from behind the upper-right corner; the chin stays hidden behind the outline' },
  'donut-floatie': { name: 'Donut floatie', feature: 'Pink-iced donut swim ring that bobs around the body', colors: ['#dbab70', '#f2a0b4', '#ffffff'], mount: 'Ring circles the base; the far half passes behind the body and the near half in front below the screen' },
  ladybug: { name: 'Ladybug', feature: 'Red spotted ladybug perched over the left shoulder', colors: ['#e8654f', '#2b2f3a'], mount: 'Shell rests on the upper-left corner behind the outline; head and feelers point up' },
  'dragon-tail': { name: 'Dragon tail', feature: 'Crimson tail with dark spines and a spade tip that sways', colors: ['#b23a48', '#7f2634'], mount: 'Root emerges from behind the lower-left edge; the tail curls up beside the arm' },
  'drone-buddy': { name: 'Drone buddy', feature: 'White quadcopter with a camera eye and spinning rotors', colors: ['#f4f6fb', '#3c4658', '#4de3ff'], mount: 'Hovers above the left shoulder on a cable that meets behind the body' },
  'shade-tree': { name: 'Shade tree', feature: 'Round leafy canopy on a short trunk, leaves gently swaying', colors: ['#6fbf73', '#3f8f4f', '#805840'], mount: 'Trunk rises from behind the top edge; the canopy spreads behind the antenna or hat' },
  'tesla-coils': { name: 'Tesla coils', feature: 'Two coil towers with ring tops and a crackling arc between them', colors: ['#c9d2ff', '#8b95a5', '#4de3ff'], mount: 'Towers stand on struts behind both shoulders; the arc bridges their tops above the head' },
  'great-wave': { name: 'Great wave', feature: 'Prussian-blue wave whose clawed curl breaks toward the robot', colors: ['#1e3f8f', '#5fb3ec', '#fff8e6'], mount: 'Swell carries the base; the curl rises beside the left arm' },
  'cloud-dragon': { name: 'Cloud dragon', feature: 'Front-facing jade dragon riding auspicious clouds; its tail whips and its eyes glow', colors: ['#2f9e7a', '#a7e8cf', '#f6b500'], mount: 'Head over the left shoulder with a foreleg hooked on it; the body arches behind the antenna and down the right side, with one cloud in front and two behind' },

  stripes: { name: 'Stripes', feature: 'Diagonal light stripes across the body and arms', colors: ['#ffffff'], mount: 'One continuous overlay across the body and arms; reads through every palette' },
  split: { name: 'Split', feature: 'Two-tone body with a lighter right half', colors: ['#ffffff'], mount: 'One overlay across the body and arms; each arm keeps its half in every pose' },
  hoops: { name: 'Hoops', feature: 'Wide light bands ringing the body and arms', colors: ['#ffffff'], mount: 'Bands stay level on the body; a raised arm crosses them at an angle' },
  sunburst: { name: 'Sunburst', feature: 'Light rays fanning out from the screen across the rim', colors: ['#ffffff'], mount: 'Rays radiate from the screen center over the body and arms' },
  dipped: { name: 'Dipped', feature: 'Lower body dipped in a deeper shade of its color', colors: ['#0b1020'], mount: 'The dip line runs level across the lower arms; a raised arm lifts out of it' },
  pinwheel: { name: 'Pinwheel', feature: 'Four broad light blades slowly turning around the screen', colors: ['#ffffff'], mount: 'Blades turn about the screen center over the body and arms' },
  quartered: { name: 'Quartered', feature: 'Opposite quarters of the body in a lighter shade', colors: ['#ffffff'], mount: 'Quarters meet at the screen center; each arm is half light, half base' },
  bowtie: { name: 'Bowtie', feature: 'Light wedges spreading from the screen to both arms', colors: ['#ffffff'], mount: 'Wedges meet at the screen center; the arms stay light in every pose' },
  sonar: { name: 'Sonar', feature: 'Rings of light pulsing outward from the screen', colors: ['#ffffff'], mount: 'Rings are centered on the screen and reach the arms last' },
  tide: { name: 'Tide', feature: 'A deeper shade whose wavy waterline rises and ebbs up the body', colors: ['#0b1020'], mount: 'Waves cross both lower arms at rest and climb the body as the tide rises' },
  chrome: { name: 'Chrome', feature: 'Mirror steel with a horizon line and a sweeping sheen', colors: ['#f4f7fb', '#9aa6b8', '#3c4658'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  gold: { name: 'Gold', feature: 'Polished gold with a sweeping sheen', colors: ['#f6d365', '#b8862c', '#fff3c4'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  lava: { name: 'Lava', feature: 'Molten rock whose glow flows between ember red and bright orange', colors: ['#e8451f', '#ffb347', '#4a1208'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  holographic: { name: 'Holographic', feature: 'Iridescent foil whose colors flow across the body', colors: ['#ff8ad4', '#8ad8ff', '#c9ff8a'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  galaxy: { name: 'Galaxy', feature: 'Deep space nebula that drifts between violet and blue with twinkling stars', colors: ['#4c1d95', '#2563eb', '#ffffff'], mount: 'Replaces the body and arm paint; stars twinkle on the surface' },
  bumblebee: { name: 'Bumblebee', feature: 'Warm yellow and charcoal bands across the body', colors: ['#f6c343', '#2b2f3a'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  aurora: { name: 'Aurora', feature: 'Night sky whose green and violet light ripples across the body', colors: ['#1fbf8f', '#5eead4', '#7c6cf0'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  terminal: { name: 'Terminal', feature: 'Dark console casing with a phosphor scan line rolling down', colors: ['#111a22', '#7dff8a'], mount: 'Replaces the body and arm paint; the scan line rolls over the surface' },
  patina: { name: 'Copper patina', feature: 'Aged copper with verdigris that creeps up from below', colors: ['#b8733f', '#58b39a', '#f2b27a'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  thermal: { name: 'Thermal', feature: 'False-color heat that runs hot while the agent reasons', colors: ['#5b1fa8', '#c02a6b', '#ff7a1f'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  candy: { name: 'Candy', feature: 'Deep candy-apple red with a glossy sheen', colors: ['#c8102e', '#ff4d63', '#2a0309'], mount: 'Replaces the body and arm paint; face marks keep the palette' },
  racer: { name: 'Racer', feature: 'Powder blue with a marigold racing band', colors: ['#66a9d8', '#f28a1c'], mount: 'Replaces the body and arm paint; the band runs level across the lower arms' },
  prism: { name: 'Prism', feature: 'Smoked glass that splits light into a sliding rainbow', colors: ['#4f5580', '#ff5f6d', '#ffe066', '#4fb4ff'], mount: 'Replaces the body and arm paint; the rainbow sweeps across the surface' },
  void: { name: 'Void', feature: 'Black body circled by a glowing accretion arc', colors: ['#030206', '#6a3fd0', '#ffb04a'], mount: 'Replaces the body and arm paint; the arc circles the screen over the rim and arms' },
}

export const decorations: Decoration[] = items.map(item => ({ ...item, ...copy[item.id] }))
export const decorationOf = (id: ItemId): Decoration => ({ ...itemOf(id), ...copy[id] })
export const decorationName = (id: ItemId | 'none') => id === 'none' ? 'None' : copy[id].name
export function decorationsOf(slot: Slot): Decoration[] { return decorations.filter(item => item.slot === slot) }
export function decorationsByRarity(rarity: Rarity): Decoration[] { return decorations.filter(item => item.rarity === rarity) }
export function decorationsBySeries(series: Series): Decoration[] { return decorations.filter(item => item.series === series) }
export const rarityOrder = (rarity: Rarity) => rarities.indexOf(rarity)
export const slotOrder = (slot: Slot) => slots.indexOf(slot)
export const seriesOrder = (series: Series) => seriesIds.indexOf(series)
