export { Avatar, AppearanceAvatar, type AvatarProps, type AppearanceAvatarProps } from './Avatar.js'
export { DecorationSwatch, PrimaryDecoration, SecondaryDecoration } from './Decorations.js'

export { ComposerMascot } from './composer/ComposerMascot.js'
export type { ComposerMascotProps, ComposerMascotContext, MascotExpression, MascotLight } from './composer/types.js'
export { ComposerMascotShadow } from './composer/ComposerMascotShadow.js'
export { useComposerAvatarBehavior } from './composer/useComposerAvatarBehavior.js'
export { useMascotActiveIdle, type MascotActiveIdleAttributes, type MascotActiveIdleHandle, type MascotActiveIdleOptions } from './composer/useMascotActiveIdle.js'
export { MascotIdleStage } from './composer/MascotIdleStage.js'
export { MASCOT_SLEEP_AFTER_MS } from './composer/constants.js'
export type { MascotActiveIdle, MascotActiveIdleMotion, MascotActiveIdlePhase, MascotActiveIdlePlan, MascotIdleDirection } from './composer/constants.js'
